#!/usr/bin/env python3
"""Derive a rows_per_simd-parameterized probe body FROM the shipped crossrow kernel.

E27 could sweep NA because NA is already a template parameter. `rows_per_simd`
is a `constexpr int` in the function body, so sweeping it needs a second copy of
the body -- and a hand-copied body silently stops measuring the shipped kernel
the moment either file is edited. This generator extracts the body from
`quantized.h` at build time and applies a closed set of rewrites, each of which
must match exactly once, so the probe body IS the shipped body by construction.

`--check` re-derives and compares against the committed generated header. It is a
CONTENT assertion over the extracted template text, not a hash of `quantized.h`:
that file churned b7ae4cc0 -> b82e423f -> cafb33fe in one day with no behaviour
change, so a whole-file hash is a false alarm generator.

  python3 research/crossrow_rps_gen.py            # write generated header
  python3 research/crossrow_rps_gen.py --check    # verify it is still in sync
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

SHIPPED = pathlib.Path(
    "Vendor/mlx-swift/Source/Cmlx/mlx/mlx/backend/metal/kernels/quantized.h"
)
GENERATED = pathlib.Path("research/generated/crossrow_rps_wide.h")

SIGNATURE = "METAL_FUNC void qmv_fast_crossrow_affine4_g64_wide("
TEMPLATE_LINE = "template <typename T, int NA, bool DIRECT_NIBBLES = false>"

# (description, exact old text, exact new text). Every entry must match exactly
# once in the extracted body; anything else means the shipped kernel moved under
# the probe and the sweep would be measuring a stale structure.
REWRITES = [
    (
        "add ROWS_PER_SIMD template parameter",
        TEMPLATE_LINE,
        "template <typename T, int NA, int ROWS_PER_SIMD, bool DIRECT_NIBBLES = false>",
    ),
    (
        "rename so the probe cannot shadow the shipped symbol",
        SIGNATURE,
        "METAL_FUNC void qmv_fast_crossrow_affine4_g64_wide_rps(",
    ),
    (
        "widen the NA bound inside the probe only",
        '  static_assert(NA >= 2 && NA <= 5, "wide multi-row QMV supports NA in [2, 5]");',
        '  static_assert(NA >= 2 && NA <= 16, "probe-only NA bound; shipped bound is [2, 5]");',
    ),
    (
        "lift rows_per_simd to a template parameter",
        "  constexpr int rows_per_simd = 4;",
        "  constexpr int rows_per_simd = ROWS_PER_SIMD;",
    ),
]

HEADER = """// GENERATED by research/crossrow_rps_gen.py -- do not edit by hand.
//
// Body extracted verbatim from {src} lines {lo}-{hi}
// (extracted-body sha256 {digest}), then rewritten by exactly {n} closed
// substitutions:
{rewrite_log}//
// Nothing else differs from the shipped kernel: the k-loop, the load order, the
// qdot expression tree, the epilogue and the simd_sum reduction are the shipped
// text. Re-verify with `python3 research/crossrow_rps_gen.py --check`.

#pragma once

"""

# rows_per_simd = r covers r rows per simdgroup per body call. The frozen host
# grid (bn = 8, 2 simdgroups) requires 4 rows per simdgroup, so a probe cell with
# r < 4 is only shipped-legal if it is called 4/r times. This wrapper is the
# coverage-preserving form; it adds no body text of its own.
ROWBLOCKED = """
// Coverage-preserving form: 4/ROWS_PER_SIMD sequential row blocks per simdgroup,
// so the frozen 8-rows-per-threadgroup host geometry is still covered when
// ROWS_PER_SIMD < 4. Weight rows are still read once each; the x-side pass is
// repeated once per block.
template <typename T, int NA, int ROWS_PER_SIMD, bool DIRECT_NIBBLES = false>
METAL_FUNC void qmv_fast_crossrow_affine4_g64_rowblocked(
    const device uint32_t* w,
    const device T* scales,
    const device T* biases,
    const device T* x,
    device T* y,
    const int in_vec_size,
    const int out_vec_size,
    int first_m,
    int out_row,
    uint simd_lid) {
  static_assert(4 % ROWS_PER_SIMD == 0, "row blocks must tile 4 rows exactly");
  for (int b = 0; b < 4 / ROWS_PER_SIMD; b++) {
    qmv_fast_crossrow_affine4_g64_wide_rps<T, NA, ROWS_PER_SIMD, DIRECT_NIBBLES>(
        w, scales, biases, x, y, in_vec_size, out_vec_size, first_m,
        out_row + b * ROWS_PER_SIMD, simd_lid);
  }
}
"""


def extract(text: str) -> tuple[str, int, int]:
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if line.startswith(SIGNATURE)]
    if len(starts) != 1:
        sys.exit(f"expected exactly 1 definition of {SIGNATURE!r}, found {len(starts)}")
    start = starts[0]
    if lines[start - 1] != TEMPLATE_LINE:
        sys.exit(f"unexpected template line above the signature: {lines[start - 1]!r}")
    start -= 1
    end = next(
        (i for i in range(start, len(lines)) if lines[i] == "}"),
        None,
    )
    if end is None:
        sys.exit("no closing brace at column 0 found for the crossrow body")
    return "\n".join(lines[start : end + 1]) + "\n", start + 1, end + 1


def render(body: str, lo: int, hi: int) -> str:
    digest = hashlib.sha256(body.encode()).hexdigest()[:16]
    log = []
    out = body
    for description, old, new in REWRITES:
        if out.count(old) != 1:
            sys.exit(
                f"rewrite {description!r} matched {out.count(old)} times, expected 1.\n"
                f"  looked for: {old!r}\n"
                "  The shipped kernel changed shape; re-read it before trusting any sweep."
            )
        out = out.replace(old, new)
        log.append(f"//   - {description}\n")
    header = HEADER.format(
        src=SHIPPED,
        lo=lo,
        hi=hi,
        digest=digest,
        n=len(REWRITES),
        rewrite_log="".join(log),
    )
    return header + out + ROWBLOCKED


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    body, lo, hi = extract(SHIPPED.read_text())
    generated = render(body, lo, hi)

    if args.check:
        if not GENERATED.exists():
            sys.exit(f"{GENERATED} is missing; run without --check")
        current = GENERATED.read_text()
        if current != generated:
            sys.exit(
                f"{GENERATED} is STALE relative to {SHIPPED}.\n"
                "The probe would no longer measure the shipped kernel's structure."
            )
        print(f"OK: {GENERATED} matches {SHIPPED} lines {lo}-{hi} under {len(REWRITES)} rewrites")
        return

    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(generated)
    print(f"wrote {GENERATED} from {SHIPPED} lines {lo}-{hi}")


if __name__ == "__main__":
    main()
