#!/usr/bin/env python3
"""Derive a (rows_per_simd, values_per_thread)-parameterized probe body from the
shipped crossrow kernel.

E32 lifted `rows_per_simd` out of the body. This lifts `values_per_thread` as
well. The extraction is UNCHANGED -- `extract()` is imported from
research/crossrow_rps_gen.py rather than reimplemented, so the body text this
sweeps is byte-identical to the body E32 swept. Only the rewrite set grows, and
every added rewrite is a strict superset of E32's.

`values_per_thread` is not a free integer. Three shipped expressions encode
`16` implicitly and all three must move with it:

  bytes_per_lane      = values_per_thread * 4 bits / 8 = values_per_thread / 2
  packed[..][4]       4 uint16 words = 16 nibbles      = values_per_thread / 4
  simd_lid / 4        lanes per 64-wide quant group    = 64 / values_per_thread

The third is the hard one. `group_index` assigns ONE scale/bias per lane per
k-block, which is only correct while a lane's values stay inside one 64-element
affine group. That caps values_per_thread at 64 by arithmetic, not by taste.

  python3 research/crossrow_vpt_gen.py            # write generated header
  python3 research/crossrow_vpt_gen.py --check    # verify it is still in sync
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from crossrow_rps_gen import SHIPPED, TEMPLATE_LINE, SIGNATURE, extract  # noqa: E402

GENERATED = pathlib.Path("research/generated/crossrow_vpt_wide.h")

# (description, exact old text, exact new text). Every entry must match exactly
# once in the extracted body. The first four are E32's, unchanged except that
# the template line also gains VALUES_PER_THREAD; the last four are new and are
# exactly the places where `values_per_thread = 16` is baked into a literal.
REWRITES = [
    (
        "add ROWS_PER_SIMD and VALUES_PER_THREAD template parameters",
        TEMPLATE_LINE,
        "template <typename T, int NA, int ROWS_PER_SIMD, int VALUES_PER_THREAD,\n"
        "          bool DIRECT_NIBBLES = false>",
    ),
    (
        "rename so the probe cannot shadow the shipped symbol",
        SIGNATURE,
        "METAL_FUNC void qmv_fast_crossrow_affine4_g64_wide_vpt(",
    ),
    (
        "widen the NA bound inside the probe only",
        '  static_assert(NA >= 2 && NA <= 5, "wide multi-row QMV supports NA in [2, 5]");',
        '  static_assert(NA >= 2 && NA <= 16, "probe-only NA bound; shipped bound is [2, 5]");\n'
        '  static_assert(VALUES_PER_THREAD % 4 == 0,\n'
        '                "a lane stages whole uint16 words of 4 nibbles");\n'
        '  static_assert(VALUES_PER_THREAD <= 64,\n'
        '                "one scale/bias per lane per k-block requires a lane to stay "\n'
        '                "inside one 64-element affine group");',
    ),
    (
        "lift rows_per_simd to a template parameter",
        "  constexpr int rows_per_simd = 4;",
        "  constexpr int rows_per_simd = ROWS_PER_SIMD;",
    ),
    (
        "lift values_per_thread to a template parameter",
        "  constexpr int values_per_thread = 16;",
        "  constexpr int values_per_thread = VALUES_PER_THREAD;",
    ),
    (
        "derive bytes_per_lane from values_per_thread at 4 bits",
        "  constexpr int bytes_per_lane = 8;",
        "  constexpr int bytes_per_lane = values_per_thread / 2;\n"
        "  constexpr int words_per_lane = values_per_thread / 4;",
    ),
    (
        "size the packed staging array from values_per_thread",
        "    thread uint16_t packed[rows_per_simd][4];",
        "    thread uint16_t packed[rows_per_simd][words_per_lane];",
    ),
    (
        "stage every word the wider lane now owns",
        "      for (int i = 0; i < 4; i++) {\n"
        "        packed[r][i] = ws[i];\n"
        "      }",
        "      for (int i = 0; i < words_per_lane; i++) {\n"
        "        packed[r][i] = ws[i];\n"
        "      }",
    ),
    (
        "rescale the lanes-per-quantization-group divisor",
        "      const int group_index = row * in_vec_size_g + k / 64 + simd_lid / 4;",
        "      const int group_index =\n"
        "          row * in_vec_size_g + k / 64 + simd_lid / (64 / values_per_thread);",
    ),
    (
        "walk every staged word in the qdot loop",
        "    for (int i = 0; i < 4; i++) {\n"
        "      VF a0, a1, a2, a3;",
        "    for (int i = 0; i < words_per_lane; i++) {\n"
        "      VF a0, a1, a2, a3;",
    ),
]

HEADER = """// GENERATED by research/crossrow_vpt_gen.py -- do not edit by hand.
//
// Body extracted verbatim from {src} lines {lo}-{hi}
// (extracted-body sha256 {digest}) by the UNCHANGED E32 extractor
// research/crossrow_rps_gen.py:extract, then rewritten by exactly {n} closed
// substitutions:
{rewrite_log}//
// Nothing else differs from the shipped kernel: the k-loop structure, the load
// order, the qdot expression tree, the epilogue and the simd_sum reduction are
// the shipped text. At ROWS_PER_SIMD=4, VALUES_PER_THREAD=16 this body is
// semantically identical to the shipped one (bytes_per_lane 8, words_per_lane
// 4, simd_lid / 4). Re-verify with `python3 research/crossrow_vpt_gen.py --check`.

#pragma once

"""

ROWBLOCKED = """
// Coverage-preserving form: 4/ROWS_PER_SIMD sequential row blocks per simdgroup,
// so the frozen 8-rows-per-threadgroup host geometry is still covered when
// ROWS_PER_SIMD < 4. Weight rows are still read once each; the x-side pass is
// repeated once per block. Identical to E32's wrapper apart from carrying
// VALUES_PER_THREAD through.
template <typename T, int NA, int ROWS_PER_SIMD, int VALUES_PER_THREAD,
          bool DIRECT_NIBBLES = false>
METAL_FUNC void qmv_fast_crossrow_affine4_g64_rowblocked_vpt(
    const device uint32_t* w,
    const device T* scales,
    const device T* biases,
    const device T* x,
    device T* y,
    const int in_vec_size,
    const int out_vec_size,
    int first_m,
    int out_row,
    uint simd_lid) {
  static_assert(4 % ROWS_PER_SIMD == 0, "row blocks must tile 4 rows exactly");
  for (int b = 0; b < 4 / ROWS_PER_SIMD; b++) {
    qmv_fast_crossrow_affine4_g64_wide_vpt<
        T, NA, ROWS_PER_SIMD, VALUES_PER_THREAD, DIRECT_NIBBLES>(
        w, scales, biases, x, y, in_vec_size, out_vec_size, first_m,
        out_row + b * ROWS_PER_SIMD, simd_lid);
  }
}
"""


def render(body: str, lo: int, hi: int) -> str:
    digest = hashlib.sha256(body.encode()).hexdigest()[:16]
    log = []
    out = body
    for description, old, new in REWRITES:
        if out.count(old) != 1:
            sys.exit(
                f"rewrite {description!r} matched {out.count(old)} times, expected 1.\n"
                f"  looked for: {old!r}\n"
                "  The shipped kernel changed shape; re-read it before trusting any sweep."
            )
        out = out.replace(old, new)
        log.append(f"//   - {description}\n")
    header = HEADER.format(
        src=SHIPPED, lo=lo, hi=hi, digest=digest, n=len(REWRITES),
        rewrite_log="".join(log),
    )
    return header + out + ROWBLOCKED


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    body, lo, hi = extract(SHIPPED.read_text())
    generated = render(body, lo, hi)

    if args.check:
        if not GENERATED.exists():
            sys.exit(f"{GENERATED} is missing; run without --check")
        if GENERATED.read_text() != generated:
            sys.exit(
                f"{GENERATED} is STALE relative to {SHIPPED}.\n"
                "The probe would no longer measure the shipped kernel's structure."
            )
        print(f"OK: {GENERATED} matches {SHIPPED} lines {lo}-{hi} under {len(REWRITES)} rewrites")
        return

    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(generated)
    print(f"wrote {GENERATED} from {SHIPPED} lines {lo}-{hi}")


if __name__ == "__main__":
    main()
