#!/usr/bin/env bash
# E120 rung 5e -- the headline end-to-end measurement.
#
#   usage: research/e120_rung5e_session.sh TAG [tokens] [depth] [order] [var]
#
#   TAG     output directory name under research/out/
#   tokens  decode tokens per timed leg, default 512
#   depth   offered draft ceiling, default 8 (the ranked workflow's value)
#   order   sequence of `var` values, default
#           `off,sumtable,sumtable,off,off,sumtable,sumtable,off`
#   var     the runtime switch the legs sweep: `MLX_E120_QMV_ARM` (default),
#           `MLX_E120_QMV_ENTRY`, `MLX_E120_QMV_TABLE` or `MLX_E120_QMV_GRID`.
#           Reference rows always come from the `off`
#           arm, whichever switch the legs sweep.
#
# WHAT IS MEASURED. The headline is ABSOLUTE candidate seconds per token on
# the native-MTP leg, `parent_measured_seconds_per_token` from the trusted
# parent's own clock, with the arm as the only difference between legs. The
# local serial-to-MTP ratio is NOT the headline: a wide-QMV change speeds both
# local legs and partly cancels in that ratio.
#
# WHY NOT `benchmark-qwen-mtp.sh --local-iterate` PER ARM. That wrapper
# regenerates the reference rows and the serial control for every arm, and
# neither is part of the measured quantity. This session pays for both ONCE and
# then spends the rest of its wall clock on timed legs, which is what buys the
# replicate count CAMPAIGN RULE 39 asks for. Same trusted verb, `mtp-timed`,
# that the wrapper drives internally.
#
# THERMAL. `mtp-timed` does not consult MLXFAST_LOCAL_COOL_GATE, so this script
# runs the wrapper's own gate command, `./benchmark.sh --local-cool-gate-only`,
# immediately before every timed leg. Entry and exit GPU temperature are
# recorded per leg. Harness defect 25 does not apply here: both arms run the
# SAME binary and the arm is chosen by MLX_E120_QMV_ARM, so no leg has a rebuild in
# front of it and no arm can inherit a rebuild's cooling by construction.
#
# ARM ROUTING. MLX_E120_QMV_ARM must keep the MLX_ prefix.
# `sanitizedRuntimeWorkerEnvironment` is a strict allowlist that drops every
# MLXFAST_* name, so an MLXFAST_-prefixed override never reaches the runtime
# worker and every arm would silently time the shipped default.
#
# This is a LOCAL harness: one public fixture, reference rows generated by the
# candidate, no hidden prompt pool. It is never an official or ranked score.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

tag="${1:?usage: e120_rung5e_session.sh TAG [tokens] [depth] [order]}"
tokens="${2:-512}"
depth="${3:-8}"
order="${4:-off,sumtable,sumtable,off,off,sumtable,sumtable,off}"
var="${5:-MLX_E120_QMV_ARM}"

# `Qwen35CustomQMV.arm` and `.entry` both fall back to the shipped value for
# any raw string they do not know, so a typo here would silently time the same
# configuration twice.
case "${var}" in
  MLX_E120_QMV_ARM) legal="off replica fill_noconsume sumtable" ;;
  MLX_E120_QMV_ENTRY) legal="shared_switch tiered_switch" ;;
  # The one-pass table is only legal on tiered entry points, and
  # `Qwen35CustomQMV.widthPlan` asserts that, so a table sweep runs every leg
  # with MLX_E120_QMV_ENTRY=tiered_switch.
  MLX_E120_QMV_TABLE) legal="shipped onepass"; export MLX_E120_QMV_ENTRY=tiered_switch ;;
  MLX_E120_QMV_GRID) legal="wide tight" ;;
  # The deliverable moves the entry point and the table together, so an
  # entry-only or table-only sweep prices half of it. This pseudo-variable
  # names the three complete configurations instead. `templated` is the middle
  # arm: it changes no statement in the kernel body, only how many entry points
  # carry the width switch, so `incumbent -> templated` isolates the register
  # and residency channel and `templated -> deliverable` isolates the width
  # table. The E129 statement census predicts the second contrast is near zero
  # or adverse, so pricing them together would hide which half paid.
  MLX_E120_QMV_COMBO) legal="incumbent templated deliverable" ;;
  *) echo "e120_rung5e_session.sh: unknown sweep variable '${var}'" >&2; exit 2 ;;
esac

# Environment assignments for one leg, into the global `leg_env`.
leg_env=()
set_leg_env () {
  case "${var}" in
    MLX_E120_QMV_COMBO)
      case "$1" in
        incumbent)
          leg_env=(MLX_E120_QMV_ENTRY=shared_switch MLX_E120_QMV_TABLE=shipped) ;;
        templated)
          leg_env=(MLX_E120_QMV_ENTRY=tiered_switch MLX_E120_QMV_TABLE=shipped) ;;
        deliverable)
          leg_env=(MLX_E120_QMV_ENTRY=tiered_switch MLX_E120_QMV_TABLE=onepass) ;;
      esac
      ;;
    *) leg_env=("${var}=$1") ;;
  esac
}
for arm in ${order//,/ }; do
  case " ${legal} " in
    *" ${arm} "*) ;;
    *) echo "e120_rung5e_session.sh: '${arm}' is not a legal ${var} value" >&2; exit 2 ;;
  esac
done

out_dir="research/out/${tag}"
mkdir -p "${out_dir}"

swift_bin="${MLXFAST_SWIFT_BIN:-.build/release/mlxfast-swift}"
worker_bin=".build-worker/release/mlxfast-runtime-worker"
weights_path="${MLXFAST_WEIGHTS_PATH:-weights}"
public_golden="${MLXFAST_QWEN_MTP_LOCAL_GOLDEN_FIXTURE:-correctness_prompts/public_longcopy_gate_english_512_256.json}"

# The wrapper defaults the head to setup-qwen-mtp.sh's organizer-pinned bf16
# cache. The promoted attachment code cannot load that tree: the worker dies
# with keyNotFound(["mtp","pre_fc_norm_hidden","weight"]) before it answers the
# parent's first request. Use the declared head every other campaign leg uses.
head_dir="${E120_HEAD_DIR:-${HOME}/.cache/mlxfast/qwen3.8-27b-mtp-v1/mtp-head-declared-run}"
if [[ ! -s "${head_dir}/config.json" ]]; then
  echo "e120_rung5e_session.sh: no head at ${head_dir}; run research/fetch-declared-head.sh" >&2
  exit 1
fi

for path in "${swift_bin}" "${worker_bin}" "./benchmark.sh"; do
  if [[ ! -x "${path}" ]]; then
    echo "e120_rung5e_session.sh: missing ${path}" >&2
    exit 1
  fi
done

# One model-holding process at a time. `mtp-timed` does not run benchmark.sh's
# own resident-model guard, so do the same check here before loading 15.2 GB.
resident="$(pgrep -fl 'mlxfast-runtime-worker' 2>/dev/null)"
if [[ -n "${resident}" ]]; then
  echo "e120_rung5e_session.sh: a model-holding worker is already running:" >&2
  echo "${resident}" >&2
  exit 1
fi

head_sha256="$(shasum -a 256 "${head_dir}/model.safetensors" | cut -d' ' -f1)"
worker_sha256_start="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"
start_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
git_head="$(git rev-parse HEAD)"
git_dirty="$(git status --porcelain | wc -l | tr -d ' ')"

gpu_temp() {
  local macmon
  for macmon in "${MLXFAST_MACMON_BIN:-}" "${HOME}/bin/macmon" \
                /opt/homebrew/bin/macmon /usr/local/bin/macmon; do
    [[ -n "${macmon}" && -x "${macmon}" ]] || continue
    "${macmon}" pipe -s1 2>/dev/null | jq -r '.temp.gpu_temp_avg // empty'
    return 0
  done
  echo ""
}

cool_gate() {
  echo "--- cool gate before $1" >&2
  ./benchmark.sh --local-cool-gate-only
}

common_args=(
  --weights "${weights_path}"
  --mtp-head "${head_dir}"
)

# --- reference rows, once ----------------------------------------------------
golden_path="${out_dir}/golden-rows.json"
if [[ ! -s "${golden_path}" ]]; then
  plan_path="${out_dir}/seed-plan.json"
  jq -c '{seed_tokens: .cases[0].prompt_tokens, emitted: []}' \
    "${public_golden}" > "${plan_path}"
  cool_gate "the reference pass"
  echo "=== reference rows ($(( tokens + 1 )) rows, depth=${depth}, arm=off)"
  # GENERATED BY THE `off` ARM ON PURPOSE. If the reference came from the
  # shipped `sumtable` default, the `sumtable` legs would be checked against
  # rows their own kernel produced and `all_tokens_matched` would be circular.
  # Generating from `off` makes every `sumtable` leg a real 512-token exactness
  # gate: the custom kernel must reproduce, token for token and row for row, a
  # stream that stock MLX `quantized_matmul` produced. The `off` legs then check
  # against their own arm, which is the trivial control.
  MLX_E120_QMV_ARM=off \
  "${swift_bin}" mtp-verify "${common_args[@]}" \
    --emitted "${plan_path}" \
    --generate "$(( tokens + 1 ))" \
    --mtp-depth "${depth}" \
    --output "${golden_path}" \
    --plan-output "${out_dir}/generated-plan.json" || exit 1
fi
# `reference_self_consistent` alone is not enough: three DFlash goldens once
# shipped with that flag true while `emitted_tokens[i]` disagreed with
# `rows[i].sequential_argmax`. This is benchmark-qwen-mtp.sh's own preflight.
if ! jq -e --argjson tokens "${tokens}" '
    . as $g
    | ($g.rows | length) as $rows
    | $g.reference_self_consistent == true
      and ($g.rows | type == "array") and $rows > 0
      and ($g.emitted_tokens | type == "array")
      and ($g.emitted_tokens | length) == $rows
      and $rows >= ($tokens + 1)
      and ([range(0; $rows)
            | select($g.emitted_tokens[.] != $g.rows[.].sequential_argmax)]
           | length) == 0
  ' "${golden_path}" >/dev/null 2>&1; then
  echo "e120_rung5e_session.sh: the reference rows are not usable" >&2
  exit 1
fi

# --- serial control, once per arm --------------------------------------------
# THE PRE-REGISTERED NULL CONTROL. Serial decode runs at M=1 and
# `Qwen35CustomQMV.routable` requires m in 3...9, so the arm CANNOT reach the
# serial path. Running one serial leg per arm turns that claim into a
# falsifiable measurement: the two must agree within 0.5 %. A larger gap means
# the routing gate is admitting work it should decline, and the whole MTP-leg
# comparison is then confounded.
#
# This is not the headline denominator. The headline is absolute candidate MTP
# seconds per token; these serial legs are a routing-gate assertion.
serial_arms=""
for arm in ${order//,/ }; do
  case " ${serial_arms} " in *" ${arm} "*) ;; *) serial_arms="${serial_arms} ${arm}" ;; esac
done
for arm in ${serial_arms}; do
  serial_path="${out_dir}/serial-control.${arm}.json"
  [[ -s "${serial_path}" ]] && continue
  cool_gate "the serial control (${arm})"
  echo "=== serial control (${tokens} tokens, depth=0, ${var}=${arm})"
  set_leg_env "${arm}"
  env "${leg_env[@]}" \
  "${swift_bin}" mtp-timed "${common_args[@]}" \
    --golden "${golden_path}" \
    --tokens "${tokens}" \
    --mtp-depth 0 > "${serial_path}" || exit 1
done

# --- timed legs --------------------------------------------------------------
: > "${out_dir}/legs.jsonl"
index=0
status=0
IFS=',' read -r -a arms <<< "${order}"
for arm in "${arms[@]}"; do
  index=$((index + 1))
  label="$(printf '%02d-%s' "${index}" "${arm}")"
  report="${out_dir}/leg.${label}.json"

  cool_gate "leg ${label}"
  entry_c="$(gpu_temp)"
  leg_start="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "=== leg ${label}: ${var}=${arm} tokens=${tokens} depth=${depth} entry=${entry_c}C"

  # Worker assertion BEFORE the leg. The binary is never rebuilt inside this
  # session, so the certificate that matters per leg is that the bytes did not
  # change under it. Re-running the full rebuild-and-assert script here would
  # itself be a rebuild in front of a leg -- harness defect 25 -- so hash
  # instead.
  worker_before="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"

  # The pipeline log is the warmup gate for a multi-pipeline entry point. It
  # records the dispatch ordinal at which each QMV specialization and each
  # verify width was first reached, so a pipeline that first compiled inside
  # the timed window is visible after the fact.
  set_leg_env "${arm}"
  env "${leg_env[@]}" \
      "MLX_E120_QMV_PIPELINE_LOG=${PWD}/${out_dir}/pipelines.${label}.json" \
  "${swift_bin}" mtp-timed "${common_args[@]}" \
    --golden "${golden_path}" \
    --tokens "${tokens}" \
    --mtp-depth "${depth}" > "${report}"
  leg_status=$?
  [[ "${leg_status}" -eq 0 ]] || status="${leg_status}"

  worker_after="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"
  exit_c="$(gpu_temp)"
  leg_end="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  jq -n --arg arm "${arm}" --arg label "${label}" --arg report "${report}" \
        --arg entry "${entry_c}" --arg exit "${exit_c}" \
        --arg started "${leg_start}" --arg finished "${leg_end}" \
        --arg wbefore "${worker_before}" --arg wafter "${worker_after}" \
        --argjson status "${leg_status}" \
    '{arm: $arm, label: $label, report: $report,
      gpu_temp_entry_c: ($entry | tonumber? // null),
      gpu_temp_exit_c: ($exit | tonumber? // null),
      started_utc: $started, finished_utc: $finished, status: $status,
      worker_sha256_before: $wbefore, worker_sha256_after: $wafter,
      worker_unchanged: ($wbefore == $wafter)}' \
    >> "${out_dir}/legs.jsonl"
done

worker_sha256_end="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"

{
  echo "experiment=qwen38-r1-e120-own-the-qmv-dispatch"
  echo "rung=5e"
  echo "harness=local"
  echo "instrument=mtp-timed"
  echo "tokens=${tokens}"
  echo "offered_draft_depth=${depth}"
  echo "order=${order}"
  echo "sweep_variable=${var}"
  echo "entry=${MLX_E120_QMV_ENTRY:-tiered_switch (default)}"
  echo "table=${MLX_E120_QMV_TABLE:-shipped (default)}"
  echo "grid=${MLX_E120_QMV_GRID:-wide (default)}"
  echo "head_dir=${head_dir}"
  echo "head_safetensors_sha256=${head_sha256}"
  echo "worker_sha256_start=${worker_sha256_start}"
  echo "worker_sha256_end=${worker_sha256_end}"
  echo "started_utc=${start_iso}"
  echo "finished_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "git_head=${git_head}"
  echo "git_dirty=${git_dirty}"
  echo "host=$(hostname)"
  echo "chip=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)"
  echo "memory_gib=$(( $(sysctl -n hw.memsize) / 1073741824 ))"
  echo "toolchain=$(swift --version 2>&1 | head -1)"
  echo "cool_gate_command=./benchmark.sh --local-cool-gate-only"
  echo "cool_gate_passed_real_gate=true"
  echo "gate_qualified_for_timing=true"
  echo "official_or_ranked_score=false"
  echo "status=${status}"
} > "${out_dir}/meta.txt"

cat "${out_dir}/meta.txt"
exit "${status}"
