#!/usr/bin/env bash
# E120 rung 5e -- the headline end-to-end measurement.
#
#   usage: research/e120_rung5e_session.sh TAG [tokens] [depth] [order]
#
#   TAG     output directory name under research/out/
#   tokens  decode tokens per timed leg, default 512
#   depth   offered draft ceiling, default 8 (the ranked workflow's value)
#   order   arm sequence of Qwen35CustomQMV.Arm raw values, default
#           `off,sumtable,sumtable,off,off,sumtable,sumtable,off`
#
# WHAT IS MEASURED. The headline is ABSOLUTE candidate seconds per token on
# the native-MTP leg, `parent_measured_seconds_per_token` from the trusted
# parent's own clock, with the arm as the only difference between legs. The
# local serial-to-MTP ratio is NOT the headline: a wide-QMV change speeds both
# local legs and partly cancels in that ratio.
#
# WHY NOT `benchmark-qwen-mtp.sh --local-iterate` PER ARM. That wrapper
# regenerates the reference rows and the serial control for every arm, and
# neither is part of the measured quantity. This session pays for both ONCE and
# then spends the rest of its wall clock on timed legs, which is what buys the
# replicate count CAMPAIGN RULE 39 asks for. Same trusted verb, `mtp-timed`,
# that the wrapper drives internally.
#
# THERMAL. `mtp-timed` does not consult MLXFAST_LOCAL_COOL_GATE, so this script
# runs the wrapper's own gate command, `./benchmark.sh --local-cool-gate-only`,
# immediately before every timed leg. Entry and exit GPU temperature are
# recorded per leg. Harness defect 25 does not apply here: both arms run the
# SAME binary and the arm is chosen by MLX_E120_QMV_ARM, so no leg has a rebuild in
# front of it and no arm can inherit a rebuild's cooling by construction.
#
# ARM ROUTING. MLX_E120_QMV_ARM must keep the MLX_ prefix.
# `sanitizedRuntimeWorkerEnvironment` is a strict allowlist that drops every
# MLXFAST_* name, so an MLXFAST_-prefixed override never reaches the runtime
# worker and every arm would silently time the shipped default.
#
# This is a LOCAL harness: one public fixture, reference rows generated by the
# candidate, no hidden prompt pool. It is never an official or ranked score.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

tag="${1:?usage: e120_rung5e_session.sh TAG [tokens] [depth] [order]}"
tokens="${2:-512}"
depth="${3:-8}"
order="${4:-off,sumtable,sumtable,off,off,sumtable,sumtable,off}"

# `Qwen35CustomQMV.arm` falls back to `sumtable` for any raw value it does not
# know, so a typo here would silently time the shipped arm twice.
for arm in ${order//,/ }; do
  case "${arm}" in
    off|replica|fill_noconsume|sumtable) ;;
    *) echo "e120_rung5e_session.sh: unknown arm '${arm}'" >&2; exit 2 ;;
  esac
done

out_dir="research/out/${tag}"
mkdir -p "${out_dir}"

swift_bin="${MLXFAST_SWIFT_BIN:-.build/release/mlxfast-swift}"
worker_bin=".build-worker/release/mlxfast-runtime-worker"
weights_path="${MLXFAST_WEIGHTS_PATH:-weights}"
public_golden="${MLXFAST_QWEN_MTP_LOCAL_GOLDEN_FIXTURE:-correctness_prompts/public_longcopy_gate_english_512_256.json}"

# The wrapper defaults the head to setup-qwen-mtp.sh's organizer-pinned bf16
# cache. The promoted attachment code cannot load that tree: the worker dies
# with keyNotFound(["mtp","pre_fc_norm_hidden","weight"]) before it answers the
# parent's first request. Use the declared head every other campaign leg uses.
head_dir="${E120_HEAD_DIR:-${HOME}/.cache/mlxfast/qwen3.8-27b-mtp-v1/mtp-head-declared-run}"
if [[ ! -s "${head_dir}/config.json" ]]; then
  echo "e120_rung5e_session.sh: no head at ${head_dir}; run research/fetch-declared-head.sh" >&2
  exit 1
fi

for path in "${swift_bin}" "${worker_bin}" "./benchmark.sh"; do
  if [[ ! -x "${path}" ]]; then
    echo "e120_rung5e_session.sh: missing ${path}" >&2
    exit 1
  fi
done

# One model-holding process at a time. `mtp-timed` does not run benchmark.sh's
# own resident-model guard, so do the same check here before loading 15.2 GB.
resident="$(pgrep -fl 'mlxfast-runtime-worker' 2>/dev/null)"
if [[ -n "${resident}" ]]; then
  echo "e120_rung5e_session.sh: a model-holding worker is already running:" >&2
  echo "${resident}" >&2
  exit 1
fi

head_sha256="$(shasum -a 256 "${head_dir}/model.safetensors" | cut -d' ' -f1)"
worker_sha256_start="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"
start_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
git_head="$(git rev-parse HEAD)"
git_dirty="$(git status --porcelain | wc -l | tr -d ' ')"

gpu_temp() {
  local macmon
  for macmon in "${MLXFAST_MACMON_BIN:-}" "${HOME}/bin/macmon" \
                /opt/homebrew/bin/macmon /usr/local/bin/macmon; do
    [[ -n "${macmon}" && -x "${macmon}" ]] || continue
    "${macmon}" pipe -s1 2>/dev/null | jq -r '.temp.gpu_temp_avg // empty'
    return 0
  done
  echo ""
}

cool_gate() {
  echo "--- cool gate before $1" >&2
  ./benchmark.sh --local-cool-gate-only
}

common_args=(
  --weights "${weights_path}"
  --mtp-head "${head_dir}"
)

# --- reference rows, once ----------------------------------------------------
golden_path="${out_dir}/golden-rows.json"
if [[ ! -s "${golden_path}" ]]; then
  plan_path="${out_dir}/seed-plan.json"
  jq -c '{seed_tokens: .cases[0].prompt_tokens, emitted: []}' \
    "${public_golden}" > "${plan_path}"
  cool_gate "the reference pass"
  echo "=== reference rows ($(( tokens + 1 )) rows, depth=${depth})"
  "${swift_bin}" mtp-verify "${common_args[@]}" \
    --emitted "${plan_path}" \
    --generate "$(( tokens + 1 ))" \
    --mtp-depth "${depth}" \
    --output "${golden_path}" \
    --plan-output "${out_dir}/generated-plan.json" || exit 1
fi
if ! jq -e --argjson tokens "${tokens}" '
    .reference_self_consistent == true
    and (.rows | length) >= ($tokens + 1)
  ' "${golden_path}" >/dev/null 2>&1; then
  echo "e120_rung5e_session.sh: the reference rows are not usable" >&2
  exit 1
fi

# --- serial control, once ----------------------------------------------------
# Charged to both arms equally and unaffected by MLX_E120_QMV_ARM: serial decode
# runs at M=1 and `Qwen35CustomQMV.routable` declines every width below 3.
serial_path="${out_dir}/serial-control.json"
if [[ ! -s "${serial_path}" ]]; then
  cool_gate "the serial control"
  echo "=== serial control (${tokens} tokens, depth=0)"
  "${swift_bin}" mtp-timed "${common_args[@]}" \
    --golden "${golden_path}" \
    --tokens "${tokens}" \
    --mtp-depth 0 > "${serial_path}" || exit 1
fi

# --- timed legs --------------------------------------------------------------
: > "${out_dir}/legs.jsonl"
index=0
status=0
IFS=',' read -r -a arms <<< "${order}"
for arm in "${arms[@]}"; do
  index=$((index + 1))
  label="$(printf '%02d-%s' "${index}" "${arm}")"
  report="${out_dir}/leg.${label}.json"

  cool_gate "leg ${label}"
  entry_c="$(gpu_temp)"
  leg_start="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "=== leg ${label}: MLX_E120_QMV_ARM=${arm} tokens=${tokens} depth=${depth} entry=${entry_c}C"

  MLX_E120_QMV_ARM="${arm}" \
  "${swift_bin}" mtp-timed "${common_args[@]}" \
    --golden "${golden_path}" \
    --tokens "${tokens}" \
    --mtp-depth "${depth}" > "${report}"
  leg_status=$?
  [[ "${leg_status}" -eq 0 ]] || status="${leg_status}"

  exit_c="$(gpu_temp)"
  leg_end="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  jq -n --arg arm "${arm}" --arg label "${label}" --arg report "${report}" \
        --arg entry "${entry_c}" --arg exit "${exit_c}" \
        --arg started "${leg_start}" --arg finished "${leg_end}" \
        --argjson status "${leg_status}" \
    '{arm: $arm, label: $label, report: $report,
      gpu_temp_entry_c: ($entry | tonumber? // null),
      gpu_temp_exit_c: ($exit | tonumber? // null),
      started_utc: $started, finished_utc: $finished, status: $status}' \
    >> "${out_dir}/legs.jsonl"
done

worker_sha256_end="$(shasum -a 256 "${worker_bin}" | cut -d' ' -f1)"

{
  echo "experiment=qwen38-r1-e120-own-the-qmv-dispatch"
  echo "rung=5e"
  echo "harness=local"
  echo "instrument=mtp-timed"
  echo "tokens=${tokens}"
  echo "offered_draft_depth=${depth}"
  echo "order=${order}"
  echo "head_dir=${head_dir}"
  echo "head_safetensors_sha256=${head_sha256}"
  echo "worker_sha256_start=${worker_sha256_start}"
  echo "worker_sha256_end=${worker_sha256_end}"
  echo "started_utc=${start_iso}"
  echo "finished_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "git_head=${git_head}"
  echo "git_dirty=${git_dirty}"
  echo "host=$(hostname)"
  echo "chip=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)"
  echo "memory_gib=$(( $(sysctl -n hw.memsize) / 1073741824 ))"
  echo "toolchain=$(swift --version 2>&1 | head -1)"
  echo "cool_gate_command=./benchmark.sh --local-cool-gate-only"
  echo "cool_gate_passed_real_gate=true"
  echo "gate_qualified_for_timing=true"
  echo "official_or_ranked_score=false"
  echo "status=${status}"
} > "${out_dir}/meta.txt"

cat "${out_dir}/meta.txt"
exit "${status}"
