#!/usr/bin/env bash
# E124 stage 1 -- acceptance of the four island arms, STRATIFIED by regime.
#
#   usage: E124_H_SEEDS="benchfixture beagle_a ..." \
#          E124_L_SEEDS="medicine travel ..." \
#          research/e124_stage1_session.sh
#
# NOT A TIMING SESSION. Every leg runs with the per-round phase trace on, so no
# seconds figure produced here measures anything. The legs record
# `timing_valid=false`, `cool_gate_passed_real_gate=false` and
# `gate_qualified_for_timing=false` verbatim. Stage 2 owns timing.
#
# STRATA (F92). Stratum H is the median-carrying regime and is decisive; the
# 0.21 pt kill line applies there only. Stratum L is the legacy prose corpus,
# which accepts in the zero-weight cluster; it informs the mechanism and cannot
# kill or pass an arm.
#
# WHICH BINARY CARRIES THE ARM. `mlxfast-swift` is the trusted parent, and
# Package.swift gives MLXFastCLI no dependency on MLXLLM or MLXFastModel. It
# holds no model code, so no assertion on it can ever witness a Qwen35.swift
# edit; it spawns `.build-worker/release/mlxfast-runtime-worker`, which is the
# one artifact that carries the arm selector. The selector therefore has to
# survive `sanitizedRuntimeWorkerEnvironment`, which starts from an empty
# environment and forwards only an exact key list plus the prefixes
# `DARKBLOOM_ DYLD_ LC_ METAL_ MLX_ MTL_`. That is why the variable is spelled
# `DARKBLOOM_QWEN_MTP_ISLAND_ARM` and why the witness is written into
# `MLX_QWEN_MTP_TRACE_PATH`.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ARMS=(all none q kv)
read -r -a H_SEEDS <<< "${E124_H_SEEDS:-benchfixture}"
read -r -a L_SEEDS <<< "${E124_L_SEEDS:-}"

BUILD_ARGS=()
[[ "${E124_SKIP_BUILD:-0}" == "1" ]] && BUILD_ARGS=(--no-build)
senpai/rebuild-and-assert-worker.sh ${BUILD_ARGS[@]+"${BUILD_ARGS[@]}"} \
  --require DARKBLOOM_QWEN_MTP_ISLAND_ARM \
  --require 'qwen-mtp-island-arm: ' \
  --require-symbol Qwen35IslandArm || exit 1

goldens=".mlxfast-private/e122/goldens"
status=0

# `all` runs first on purpose. It is the shipped install path, so any reference
# rows generated during this session are generated by the control arm and never
# by an arm under test.
for arm in "${ARMS[@]}"; do
  if [[ "${arm}" != "all" ]]; then
    for id in "${H_SEEDS[@]}" ${L_SEEDS[@]+"${L_SEEDS[@]}"}; do
      [[ -s "${goldens}/${id}-rows-513.json" ]] || {
        echo "e124_stage1_session: ${arm}: no control-generated golden for ${id}" >&2
        exit 1; }
    done
  fi
  echo "=== e124 stage 1: arm ${arm} ==="
  DARKBLOOM_QWEN_MTP_ISLAND_ARM="${arm}" \
  E122_RUNS_DIR="runs-e124-arm-${arm}" \
    research/e122_rung0_session.sh "${H_SEEDS[@]}" ${L_SEEDS[@]+"${L_SEEDS[@]}"} \
    || status=1

  # The arm witness is written by the model itself, so it is the only proof
  # that the leg ran the arm the driver asked for.
  for id in "${H_SEEDS[@]}" ${L_SEEDS[@]+"${L_SEEDS[@]}"}; do
    trace=".mlxfast-private/e122/runs-e124-arm-${arm}/${id}/trace.txt"
    witness="$(grep -m1 '^qwen-mtp-island-arm: ' "${trace}" 2>/dev/null)"
    echo "witness ${arm} ${id}: ${witness:-<ABSENT>}"
    case "${witness}" in
      "qwen-mtp-island-arm: ${arm} "*) ;;
      *) echo "e124_stage1_session: ${arm}/${id} witness does not name the arm" >&2
         status=1 ;;
    esac
  done
done

strata=(--stratum "H=$(IFS=,; echo "${H_SEEDS[*]}")")
if ((${#L_SEEDS[@]})); then
  strata+=(--stratum "L=$(IFS=,; echo "${L_SEEDS[*]}")")
fi
python3 research/e124_accept.py "${strata[@]}"

exit "${status}"
