#!/usr/bin/env bash
# Research-only (qwen38-r1-e168-margin-clamp-calibration): collect the
# per-round schedule signal across varied prose under one draft-depth arm.
#
#   research/e168_collect.sh ARMS ID [ID ...]
#
#   ARMS  adapt   the shipped adaptive schedule. Measures how often the margin
#                 clamp binds and how much offered depth it removes in
#                 production. Its acceptance observations are CENSORED by the
#                 clamp under test, so no calibration curve may be fitted here.
#           pN    MLX_E159_FIXED_DRAFT_DEPTH=N. Proposes N drafts every round
#                 whatever the margin says, so it observes acceptance at
#                 positions the clamp would have refused to draft. This is the
#                 uncensored leg and the only valid source for the curve.
#
# COUNTS ONLY. e37-run.sh sets MLXFAST_LOCAL_COOL_GATE=0 and records
# `gate_qualified_for_timing=false`; no number produced here is a timing
# measurement. The phase trace is ON, which perturbs round wall time, which is
# a second reason nothing here may be read as a timing result.
#
# Goldens are expected under ${E168_ROOT}/goldens, one per prompt, generated by
#   E11_GOLDEN_DIR=.mlxfast-private/e168/goldens E11_GOLDEN_STEPS=512 \
#     research/e11-golden.sh PROMPT.txt ...
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# ARMS is a comma list. Both arms of a prompt run back to back and the order
# alternates from prompt to prompt, so an unfinished matrix still holds
# complete prompt pairs and no arm sits systematically earlier in the session.
arms="${1:?usage: research/e168_collect.sh ARMS ID [ID ...]}"
shift
(($#)) || { echo "e168_collect: need at least one prompt id" >&2; exit 2; }

root="${E168_ROOT:-${PWD}/.mlxfast-private/e168}"
out_root="${E168_OUT:-${PWD}/research/out/e168}"

IFS=',' read -r -a arm_list <<<"${arms}"
for arm in "${arm_list[@]}"; do
  case "${arm}" in
    adapt|p[0-8]) ;;
    *) echo "e168_collect: arm must be adapt or pN for N in 0..8" >&2; exit 2 ;;
  esac
done

# A stale `.build-worker` twin writes round lines without the schedule
# snapshot, and benchmark-qwen-mtp.sh never rebuilds it. Fail before the GPU
# time, not after it.
research/e168_build.sh || exit 1

export E37_ROOT="${root}"
export E37_TOKENS="${E168_TOKENS:-512}"
export E37_GOLDEN_STEPS=512
export E37_TRACE=1

status=0
index=0
for id in "$@"; do
  order=("${arm_list[@]}")
  ((index % 2)) && order=($(printf '%s\n' "${arm_list[@]}" | tail -r))
  for arm in "${order[@]}"; do
    case "${arm}" in
      adapt) unset MLX_E159_FIXED_DRAFT_DEPTH ;;
      *) export MLX_E159_FIXED_DRAFT_DEPTH="${arm#p}" ;;
    esac
    echo "=== e168_collect: arm=${arm} prompt=${id} ==="
    research/e37-run.sh --census "${id}" || { status=1; break 2; }
    dest="${out_root}/${arm}/${id}"
    mkdir -p "$(dirname "${dest}")"
    rm -rf "${dest}"
    mv "${root}/runs/${id}" "${dest}" || { status=1; break 2; }
    {
      echo "e168_arm=${arm}"
      echo "fixed_draft_depth=${MLX_E159_FIXED_DRAFT_DEPTH:-unset}"
      echo "rounds_traced=$(grep -c '^mtp-trace: round=' "${dest}/trace.txt")"
    } >> "${dest}/meta.txt"
  done
  index=$((index + 1))
done
exit "${status}"
