#!/usr/bin/env bash
# Research-only (qwen38-r1-e168-margin-clamp-calibration): collect the
# per-round schedule signal across varied prose under one draft-depth arm.
#
#   research/e168_collect.sh ARMS ID [ID ...]
#
#   ARMS  adapt   the shipped adaptive schedule. Measures how often the margin
#                 clamp binds and how much offered depth it removes in
#                 production. Its acceptance observations are CENSORED by the
#                 clamp under test, so no calibration curve may be fitted here.
#           pN    MLX_E159_FIXED_DRAFT_DEPTH=N. Proposes N drafts every round
#                 whatever the margin says, so it observes acceptance at
#                 positions the clamp would have refused to draft. This is the
#                 uncensored leg and the only valid source for the curve.
#
# COUNTS ONLY. e37-run.sh sets MLXFAST_LOCAL_COOL_GATE=0 and records
# `gate_qualified_for_timing=false`; no number produced here is a timing
# measurement. The phase trace is ON, which perturbs round wall time, which is
# a second reason nothing here may be read as a timing result.
#
# Goldens are expected under ${E168_ROOT}/goldens, one per prompt, generated by
#   E11_GOLDEN_DIR=.mlxfast-private/e168/goldens E11_GOLDEN_STEPS=512 \
#     research/e11-golden.sh PROMPT.txt ...
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# ARMS is a comma list. Both arms of a prompt run back to back and the order
# alternates from prompt to prompt, so an unfinished matrix still holds
# complete prompt pairs and no arm sits systematically earlier in the session.
arms="${1:?usage: research/e168_collect.sh ARMS ID [ID ...]}"
shift
(($#)) || { echo "e168_collect: need at least one prompt id" >&2; exit 2; }

root="${E168_ROOT:-${PWD}/.mlxfast-private/e168}"
out_root="${E168_OUT:-${PWD}/research/out/e168}"

IFS=',' read -r -a arm_list <<<"${arms}"
for arm in "${arm_list[@]}"; do
  case "${arm}" in
    adapt|p[0-8]) ;;
    *) echo "e168_collect: arm must be adapt or pN for N in 0..8" >&2; exit 2 ;;
  esac
done

# A stale `.build-worker` twin writes round lines without the schedule
# snapshot, and benchmark-qwen-mtp.sh never rebuilds it. Fail before the GPU
# time, not after it.
research/e168_build.sh || exit 1

export E37_ROOT="${root}"
export E37_TOKENS="${E168_TOKENS:-512}"
export E37_GOLDEN_STEPS=512
# E168_TRACE=0 drops the per-round trace, which is what makes a leg's wall
# time usable. The counts then come only from the trusted parent's own
# per-round record, so a trace-free pass measures time but cannot answer a
# schedule question. Never read both from one pass.
export E37_TRACE="${E168_TRACE:-1}"
# e37-run.sh looks for macmon under ~/bin. Point it at the installed binary so
# entry and exit GPU temperature are recorded for every arm, which the ungated
# timing mode requires.
export MLXFAST_MACMON_BIN="${MLXFAST_MACMON_BIN:-/opt/homebrew/bin/macmon}"

status=0
index=0
for id in "$@"; do
  order=("${arm_list[@]}")
  # E168_ABBA=1 runs A B B A inside one prompt so a monotone thermal drift
  # cancels to first order within the pair, instead of only across prompts.
  if [[ "${E168_ABBA:-0}" == 1 ]]; then
    order=("${arm_list[@]}" $(printf '%s\n' "${arm_list[@]}" | tail -r))
  elif ((index % 2)); then
    order=($(printf '%s\n' "${arm_list[@]}" | tail -r))
  fi
  for arm in "${order[@]}"; do
    case "${arm}" in
      adapt) unset MLX_E159_FIXED_DRAFT_DEPTH ;;
      *) export MLX_E159_FIXED_DRAFT_DEPTH="${arm#p}" ;;
    esac
    echo "=== e168_collect: arm=${arm} prompt=${id} ==="
    research/e37-run.sh --census "${id}" || { status=1; break 2; }
    # An ABBA session runs an arm twice on one prompt, so the replicate has to
    # keep its own directory or the second leg would erase the first.
    dest="${out_root}/${arm}/${id}"
    replicate=1
    while [[ -e "${dest}" ]]; do
      replicate=$((replicate + 1))
      dest="${out_root}/${arm}/${id}.r${replicate}"
    done
    mkdir -p "$(dirname "${dest}")"
    mv "${root}/runs/${id}" "${dest}" || { status=1; break 2; }
    {
      echo "e168_arm=${arm}"
      echo "e168_replicate=${replicate}"
      echo "fixed_draft_depth=${MLX_E159_FIXED_DRAFT_DEPTH:-unset}"
      if [[ -s "${dest}/trace.txt" ]]; then
        echo "rounds_traced=$(grep -c '^mtp-trace: round=' "${dest}/trace.txt")"
      else
        echo "rounds_traced=0"
      fi
    } >> "${dest}/meta.txt"
  done
  index=$((index + 1))
done
exit "${status}"
