"""Generate the E213 Metal probe source for the QMV group-partition plans.

Research-only. Reads `qwen35E120QMVHeader` from the shipped Swift file and emits
one `.metal` translation unit that holds:

  * `plan_<name>` kernels, one per width-plan table, each reproducing the
    `qwen35E120QMVSource` switch over `qmv_m`, so the register allocation of a
    whole plan is measurable;
  * `ipg_M_IPG` kernels, one per legal `(m, IPG)` pair, so the per-instantiation
    register cliff is measurable.

The switch text mirrors `qwen35E120QMVSource`; it is not the shipped code path.
The measured quantity is a comparison between plans compiled from the same
extracted header, so a formatting difference cannot bias one plan over another.

    python3 research/e213_probe_gen.py OUT.metal
"""

import re
import sys

SWIFT = "Vendor/mlx-swift-lm/Libraries/MLXLLM/Models/Qwen35.swift"

PLANS = {
    # E120 as shipped before E208: three weight passes at m = 9.
    "e120legacy": [(2, 2), (3, 3), (4, 4), (5, 5), (6, 3), (7, 4), (8, 4), (9, 3)],
    # The maintained base after E208 r1.
    "shipped": [(2, 2), (3, 3), (4, 4), (5, 5), (6, 3), (7, 4), (8, 4), (9, 5)],
    # E213 candidate family: rows per group raised toward 5 at m = 6, 7 and 8.
    # (6, 5) does not exist, so m = 6 takes the widest legal first group, 4.
    "retuned": [(2, 2), (3, 3), (4, 4), (5, 5), (6, 4), (7, 5), (8, 5), (9, 5)],
    # The single-pass form E195 measured and rejected at m = 7 and m = 8.
    "singlepass": [(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 3)],
}

SIGNATURE = """
kernel void {name}(
    const device uint32_t* w [[buffer(0)]],
    const device bfloat16_t* scales [[buffer(1)]],
    const device bfloat16_t* biases [[buffer(2)]],
    const device bfloat16_t* x [[buffer(3)]],
    const device float* xsums [[buffer(4)]],
    device bfloat16_t* y [[buffer(5)]],
    const device int* shape [[buffer(6)]],
    uint3 qmv_tid [[threadgroup_position_in_grid]],
    uint qmv_lid [[thread_index_in_simdgroup]],
    uint qmv_sgid [[simdgroup_index_in_threadgroup]]) {{
    const int qmv_m = shape[0];
    const int qmv_k = shape[1];
    const int qmv_n = shape[2];
    const int qmv_stride = qmv_m <= 8 ? 8 : 16;
    const int qmv_out_row = int(qmv_tid.y) * 8 + int(qmv_sgid) * 4;
    const int qmv_gx = int(qmv_tid.x);
{body}
}}
"""


def header(rows_per_simd: int = 4) -> str:
    src = open(SWIFT).read()
    match = re.search(r'let qwen35E120QMVHeader = """\n(.*?)\n    """\n', src, re.S)
    if match is None:
        raise SystemExit("e213: could not read qwen35E120QMVHeader")
    text = match.group(1)
    if rows_per_simd != 4:
        text, n = re.subn(r"constexpr int rows_per_simd = 4;",
                          f"constexpr int rows_per_simd = {rows_per_simd};", text)
        if n != 1:
            raise SystemExit("e213: rows_per_simd constant not found exactly once")
    return text


def plan_body(pairs, table: bool) -> str:
    sums = "xsums" if table else "qmv_null_sums"
    flag = "true" if table else "false"
    null_decl = "" if table else "    const device float* qmv_null_sums = nullptr;\n"
    cases = "\n".join(
        f"""        case {m}:
            qwen_e120_qmv_m<{m}, {ipg}, {flag}>(
                w, scales, biases, x, {sums}, y,
                qmv_k, qmv_n, qmv_stride,
                qmv_gx, qmv_out_row, qmv_lid);
            break;"""
        for m, ipg in pairs
    )
    return f"{null_decl}    switch (qmv_m) {{\n{cases}\n        default:\n            break;\n    }}"


def single_body(m: int, ipg: int, table: bool) -> str:
    sums = "xsums" if table else "qmv_null_sums"
    flag = "true" if table else "false"
    null_decl = "" if table else "    const device float* qmv_null_sums = nullptr;\n"
    return (
        f"{null_decl}    qwen_e120_qmv_m<{m}, {ipg}, {flag}>(\n"
        f"        w, scales, biases, x, {sums}, y,\n"
        f"        qmv_k, qmv_n, qmv_stride, qmv_gx, qmv_out_row, qmv_lid);"
    )


def legal(m: int, ipg: int) -> bool:
    return m % ipg != 1


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/e213_probe.metal"
    rows_per_simd = int(sys.argv[2]) if len(sys.argv) > 2 else 4
    parts = [
        "// Generated by research/e213_probe_gen.py. Research probe, not shipped.",
        "#include <metal_stdlib>",
        "using namespace metal;",
        "typedef bfloat bfloat16_t;",
        header(rows_per_simd),
    ]
    for name, pairs in PLANS.items():
        for table in (False, True):
            suffix = "table" if table else "plain"
            parts.append(
                SIGNATURE.format(name=f"plan_{name}_{suffix}", body=plan_body(pairs, table))
            )
    for m in range(2, 10):
        for ipg in range(2, m + 1):
            if not legal(m, ipg):
                continue
            for table in (False, True):
                suffix = "table" if table else "plain"
                parts.append(
                    SIGNATURE.format(
                        name=f"ipg_{m}_{ipg}_{suffix}", body=single_body(m, ipg, table)
                    )
                )
    open(out, "w").write("\n".join(parts) + "\n")
    print(f"e213: wrote {out}")


if __name__ == "__main__":
    main()
