"""Generate the E216 Metal probe source for the two QMV weight-stream mappings.

Research-only. Reads `qwen35E120QMVHeader` from the shipped Swift file and emits
one `.metal` translation unit that holds:

  * `plan_split_*`, the shipped mapping: threadgroup `(g, y)` runs token group
    `g` over output rows `8y ..< 8y+8`;
  * `plan_coop_*`, the E216 mapping: threadgroup `y` runs BOTH token groups over
    output rows `4y ..< 4y+4`, one group per simdgroup, at every two-group
    width;
  * `ipg_M_IPG_*`, one kernel per legal `(m, IPG)` pair, so the census can show
    that E216 changes no instantiation at all.

The switch text mirrors `qwen35E120QMVSource`; it is not the shipped code path.
`Tests/MLXFastTests/E216CoopWeightStreamQMVTests.geometry` asserts the shipped
text property this file reproduces. The measured quantity is a comparison
between two mappings compiled from the same extracted header, so a formatting
difference cannot bias one mapping over the other.

    python3 research/e216_probe_gen.py OUT.metal
"""

import re
import sys

SWIFT = "Vendor/mlx-swift-lm/Libraries/MLXLLM/Models/Qwen35.swift"

# The maintained base plan (FINDING 554 scored surface): cap-8 + (9,5) staged.
STAGED = [(2, 2), (3, 3), (4, 4), (5, 5), (6, 3), (7, 4), (8, 4), (9, 5)]

SPLIT_GROUP = "int(qmv_tid.x)"
SPLIT_ROW = "int(qmv_tid.y) * 8 + int(qmv_sgid) * 4"
COOP_GROUP = "int(qmv_sgid)"
COOP_ROW = "int(qmv_tid.y) * 4"

SIGNATURE = """
kernel void {name}(
    const device uint32_t* w [[buffer(0)]],
    const device bfloat16_t* scales [[buffer(1)]],
    const device bfloat16_t* biases [[buffer(2)]],
    const device bfloat16_t* x [[buffer(3)]],
    const device float* xsums [[buffer(4)]],
    device bfloat16_t* y [[buffer(5)]],
    const device int* shape [[buffer(6)]],
    uint3 qmv_tid [[threadgroup_position_in_grid]],
    uint qmv_lid [[thread_index_in_simdgroup]],
    uint qmv_sgid [[simdgroup_index_in_threadgroup]]) {{
    const int qmv_m = shape[0];
    const int qmv_k = shape[1];
    const int qmv_n = shape[2];
    const int qmv_stride = qmv_m <= 8 ? 8 : 16;
{body}
}}
"""


def header() -> str:
    src = open(SWIFT).read()
    match = re.search(r'let qwen35E120QMVHeader = """\n(.*?)\n    """\n', src, re.S)
    if match is None:
        raise SystemExit("e216: could not read qwen35E120QMVHeader")
    return match.group(1)


def groups(m: int, ipg: int) -> int:
    return (m + ipg - 1) // ipg


def plan_body(pairs, table: bool, paired: bool) -> str:
    sums = "xsums" if table else "qmv_null_sums"
    flag = "true" if table else "false"
    null_decl = "" if table else "    const device float* qmv_null_sums = nullptr;\n"
    cases = []
    for m, ipg in pairs:
        coop = paired and groups(m, ipg) == 2
        group = COOP_GROUP if coop else SPLIT_GROUP
        row = COOP_ROW if coop else SPLIT_ROW
        cases.append(
            f"""        case {m}:
            qwen_e120_qmv_m<{m}, {ipg}, {flag}>(
                w, scales, biases, x, {sums}, y,
                qmv_k, qmv_n, qmv_stride,
                {group}, {row}, qmv_lid);
            break;"""
        )
    body = "\n".join(cases)
    return f"{null_decl}    switch (qmv_m) {{\n{body}\n        default:\n            break;\n    }}"


def single_body(m: int, ipg: int, table: bool, paired: bool) -> str:
    sums = "xsums" if table else "qmv_null_sums"
    flag = "true" if table else "false"
    null_decl = "" if table else "    const device float* qmv_null_sums = nullptr;\n"
    coop = paired and groups(m, ipg) == 2
    group = COOP_GROUP if coop else SPLIT_GROUP
    row = COOP_ROW if coop else SPLIT_ROW
    return (
        f"{null_decl}    qwen_e120_qmv_m<{m}, {ipg}, {flag}>(\n"
        f"        w, scales, biases, x, {sums}, y,\n"
        f"        qmv_k, qmv_n, qmv_stride, {group}, {row}, qmv_lid);"
    )


def legal(m: int, ipg: int) -> bool:
    return m % ipg != 1


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/e216_probe.metal"
    parts = [
        "// Generated by research/e216_probe_gen.py. Research probe, not shipped.",
        "#include <metal_stdlib>",
        "using namespace metal;",
        "typedef bfloat bfloat16_t;",
        header(),
    ]
    for name, paired in (("split", False), ("coop", True)):
        for table in (False, True):
            suffix = "table" if table else "plain"
            parts.append(
                SIGNATURE.format(
                    name=f"plan_{name}_{suffix}",
                    body=plan_body(STAGED, table, paired),
                )
            )
    for m in range(2, 10):
        for ipg in range(2, m + 1):
            if not legal(m, ipg):
                continue
            for name, paired in (("split", False), ("coop", True)):
                for table in (False, True):
                    suffix = "table" if table else "plain"
                    parts.append(
                        SIGNATURE.format(
                            name=f"ipg_{m}_{ipg}_{name}_{suffix}",
                            body=single_body(m, ipg, table, paired),
                        )
                    )
    open(out, "w").write("\n".join(parts) + "\n")
    print(f"e216: wrote {out}")


if __name__ == "__main__":
    main()
