#!/usr/bin/env python3
"""E221 step 0: what does `rows_per_simd` really cost in registers, per NA?

FINDING 549 published a `rows x NA` register grid for `qwen_e120_qmv_wide` and
FINDING 574 fitted `R(rows=4, NA) = 39.10 + 17.10*NA` from it, then predicted
the rows=2 slope by subtracting the accumulator term. Both rest on ONE witness:
the AIR lane-weighted peak-live-value heuristic in `air_kernel_stats.py`. That
heuristic is a textual linear scan, not liveness, and it never runs the AGX
register allocator, so it cannot see compiler reallocation -- which FINDING 574
names as the decisive unknown.

This probe reads the same grid with two witnesses over the same source text:

  air_lane_peak   the FINDING 549 instrument, for continuity. Reproducing
                  125/144/155/175/195 at rows=4, NA 5..9 is the control; a
                  miss means the grid, not the candidate, needs repair.
  agx registers   the REAL Apple GPU backend through `xcrun metal-tt`, for the
                  local `applegpu_g16s` and the ranked `applegpu_g17s`. This is
                  a measurement, not a proxy, and FINDING 549 never had it.

The kernel body comes from the live `qwen35E120QMVHeader` in `Qwen35.swift`, so
the probe cannot drift from the scored kernel. `rows_per_simd` is turned into a
template parameter by substituting exactly one line; every other character of
the shipped body is preserved, and the substitution count is asserted.

Two entry forms are compiled:

  f549   the recovered E213 generator entry -- `qwen_e120_qmv_m<M, IPG, flag>`
         with `out_row = tid.y * 8 + sgid * 4` and `M == IPG == NA`. This is
         the exact form behind the FINDING 549 numbers, so it is the control.
  wide   `qwen_e120_qmv_wide<NA, ROWS, flag>` called directly with the
         rows-correct geometry `out_row = tid.y * (2 * ROWS) + sgid * ROWS`.
         This is what a scored rows=2 kernel would actually launch.

Zero GPU seconds. Nothing here is timed, scored or shipped.

  python3 research/e221_register_probe.py
  python3 research/e221_register_probe.py --arch applegpu_g16s
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import agx_crossarch  # noqa: E402
from air_kernel_stats import peak_live_registers  # noqa: E402

REPO = HERE.parent
QWEN35 = REPO / "Vendor/mlx-swift-lm/Libraries/MLXLLM/Models/Qwen35.swift"
ARTIFACTS = HERE / "e221-artifacts"

ROWS = (1, 2, 3, 4)
NAS = tuple(range(2, 10))

# FINDING 549's rows=4 row, AIR lane-weighted peak live registers. The probe
# must reproduce these before any rows=2 number from it is believed.
F549_ROWS4 = {2: 67, 3: 87, 4: 106, 5: 125, 6: 144, 7: 155, 8: 175, 9: 195}
# The rest of the FINDING 549 grid, for a full-table comparison.
F549 = {
    4: F549_ROWS4,
    3: {5: 108, 6: 124, 7: 140, 8: 166, 9: 185},
    2: {5: 91, 6: 104, 7: 117, 8: 132, 9: 147},
    1: {5: 74, 6: 84, 7: 94, 8: 104, 9: 114},
}
# FINDING 574's fit of the rows=4 ladder and its rows=2 prediction.
F574_ROWS4_FIT = (39.10, 17.10)
F574_ROWS2_SLOPE = 15.10
F574_ROWS2_NA5_BRACKET = (95, 115)
# The register boundary FINDING 549 read off the AIR proxy scale.
F549_BOUNDARY = 128

# FINDING 552: this joint instantiation is miscompiled. It is compiled here for
# the register table only and must never be timed or shipped.
MISCOMPILED = {("wide", 7, 2, False), ("f549", 7, 2, False)}

PREAMBLE = """// Generated by research/e221_register_probe.py. Research probe, not shipped.
#include <metal_stdlib>
#include <metal_simdgroup>
using namespace metal;
typedef bfloat bfloat16_t;
"""

# `qwen_e120_qmv_m` reaches `qwen_e120_qmv_wide` through the shipped body, so
# the ROWS argument has to be threaded through it as well.
SUBSTITUTIONS = (
    ("template <int NA, bool USE_TABLE>", "template <int NA, int ROWS, bool USE_TABLE>"),
    ("constexpr int rows_per_simd = 4;", "constexpr int rows_per_simd = ROWS;"),
    (
        "template <int M, int IPG, bool USE_TABLE>",
        "template <int M, int IPG, int ROWS, bool USE_TABLE>",
    ),
    ("qwen_e120_qmv_wide<IPG, USE_TABLE>(", "qwen_e120_qmv_wide<IPG, ROWS, USE_TABLE>("),
    (
        "qwen_e120_qmv_wide<(TAIL >= 2 ? TAIL : 2), USE_TABLE>(",
        "qwen_e120_qmv_wide<(TAIL >= 2 ? TAIL : 2), ROWS, USE_TABLE>(",
    ),
)

SIGNATURE = """
kernel void {name}(
    const device uint32_t* w [[buffer(0)]],
    const device bfloat16_t* scales [[buffer(1)]],
    const device bfloat16_t* biases [[buffer(2)]],
    const device bfloat16_t* x [[buffer(3)]],
    const device float* xsums [[buffer(4)]],
    device bfloat16_t* y [[buffer(5)]],
    const device int* shape [[buffer(6)]],
    uint3 qmv_tid [[threadgroup_position_in_grid]],
    uint qmv_lid [[thread_index_in_simdgroup]],
    uint qmv_sgid [[simdgroup_index_in_threadgroup]]) {{
    const int qmv_m = shape[0];
    const int qmv_k = shape[1];
    const int qmv_n = shape[2];
    const int qmv_stride = qmv_m <= 8 ? 8 : 16;
    const int qmv_gx = int(qmv_tid.x);
{body}
}}
"""


def live_header() -> str:
    text = QWEN35.read_text()
    match = re.search(
        r'let qwen35E120QMVHeader = """\n(.*?)\n    """\n', text, re.S)
    if match is None:
        raise SystemExit("e221: could not read qwen35E120QMVHeader")
    return match.group(1)


def rows_parameterized(header: str) -> str:
    """The shipped body with `rows_per_simd` promoted to a template argument."""
    out = header
    for old, new in SUBSTITUTIONS:
        out, count = out.replace(old, new), out.count(old)
        if count != 1:
            raise SystemExit(
                f"e221: expected exactly one occurrence of {old!r}, found {count}")
    return out


def entry(form: str, na: int, rows: int, table: bool) -> tuple[str, str]:
    """One entry kernel: `(name, source)`."""
    sums = "xsums" if table else "qmv_null_sums"
    flag = "true" if table else "false"
    null_decl = (
        "" if table
        else "    const device float* qmv_null_sums = nullptr;\n")
    name = f"{form}_r{rows}_na{na}_{'tbl' if table else 'plain'}"
    if form == "f549":
        # The FINDING 549 entry verbatim: the rows=4 output-row geometry, and
        # the width switch collapsed to the single M == IPG == NA case.
        geometry = "    const int qmv_out_row = int(qmv_tid.y) * 8 + int(qmv_sgid) * 4;"
        call = (
            f"    qwen_e120_qmv_m<{na}, {na}, {rows}, {flag}>(\n"
            f"        w, scales, biases, x, {sums}, y,\n"
            f"        qmv_k, qmv_n, qmv_stride, qmv_gx, qmv_out_row, qmv_lid);")
    else:
        geometry = (
            f"    const int qmv_out_row = int(qmv_tid.y) * {2 * rows}"
            f" + int(qmv_sgid) * {rows};")
        call = (
            f"    qwen_e120_qmv_wide<{na}, {rows}, {flag}>(\n"
            f"        w, scales, biases, x, {sums}, y,\n"
            f"        qmv_k, qmv_n, qmv_stride, int(qmv_gx) * {na},"
            f" qmv_out_row, qmv_lid);")
    return name, SIGNATURE.format(
        name=name, body=f"{null_decl}{geometry}\n{call}")


def shipped_source(header: str) -> str:
    """A second translation unit built from the UNMODIFIED shipped header.

    The rows-parameterized body is one substituted line away from the shipped
    body, but "one line" is an argument, not evidence. This TU instantiates the
    real two-parameter `qwen_e120_qmv_wide<NA, USE_TABLE>` at its literal
    `rows_per_simd = 4`, so the rows=4 column can be compared against the
    parameterized ROWS=4 column and the parameterization itself is either
    exonerated or convicted.
    """
    parts = [PREAMBLE, header]
    for na in NAS:
        for table in (False, True):
            sums = "xsums" if table else "qmv_null_sums"
            flag = "true" if table else "false"
            null_decl = (
                "" if table
                else "    const device float* qmv_null_sums = nullptr;\n")
            body = (
                f"{null_decl}"
                "    const int qmv_out_row = int(qmv_tid.y) * 8"
                " + int(qmv_sgid) * 4;\n"
                f"    qwen_e120_qmv_m<{na}, {na}, {flag}>(\n"
                f"        w, scales, biases, x, {sums}, y,\n"
                "        qmv_k, qmv_n, qmv_stride, qmv_gx, qmv_out_row,"
                " qmv_lid);")
            parts.append(SIGNATURE.format(
                name=f"ship_na{na}_{'tbl' if table else 'plain'}", body=body))
    return "\n".join(parts) + "\n"


def arms() -> list[tuple[str, str, int, int, bool]]:
    found = []
    for form in ("f549", "wide"):
        for rows in ROWS:
            for na in NAS:
                for table in (False, True):
                    name, _ = entry(form, na, rows, table)
                    found.append((name, form, na, rows, table))
    return found


def instantiation_symbol(na: int, rows: int, table: bool) -> str:
    """The Itanium-mangled name of one `qwen_e120_qmv_wide` instantiation.

    A translation unit holding many entry points that share an instantiation
    outlines the shared body, so the entry `define` is a thin call wrapper and
    reading it reports about five registers. FINDING 549 reported the body, not
    the wrapper, so the proxy has to be read from this symbol. It is shared by
    both entry forms, which makes the proxy a property of
    `(NA, ROWS, USE_TABLE)` alone.
    """
    return (f"_Z18qwen_e120_qmv_wideILi{na}ELi{rows}ELb"
            f"{1 if table else 0}EE")


def air_peaks(source: pathlib.Path, workdir: pathlib.Path) -> dict[str, int]:
    """FINDING 549's witness: `metal -O2 -S` then `metal-opt -O3`, then the
    lane-weighted peak-live scan over each `define` body."""
    workdir.mkdir(parents=True, exist_ok=True)
    raw = workdir / "probe.ll"
    opt = workdir / "probe.opt.ll"
    subprocess.run(
        ["xcrun", "-sdk", "macosx", "metal", "-std=metal4.0", "-O2",
         "-fno-fast-math", "-S", str(source), "-o", str(raw)],
        check=True, capture_output=True, text=True)
    subprocess.run(
        ["xcrun", "-sdk", "macosx", "metal-opt", "-passes=default<O3>", "-S",
         str(raw), "-o", str(opt)],
        check=True, capture_output=True, text=True)
    bodies: dict[str, list[str]] = {}
    name = None
    for line in opt.read_text().splitlines():
        if line.startswith("define "):
            match = re.search(r"@([\w.]+)\(", line)
            name = match.group(1) if match else None
            if name:
                bodies[name] = []
        elif line == "}":
            name = None
        elif name is not None:
            bodies[name].append(line)
    return {k: peak_live_registers(v)[0] for k, v in bodies.items()}


def fit(points: dict[int, float]) -> dict[str, float] | None:
    """Least squares over `{NA: registers}`, with R^2."""
    if len(points) < 3:
        return None
    xs = sorted(points)
    n = len(xs)
    mx = sum(xs) / n
    my = sum(points[x] for x in xs) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (points[x] - my) for x in xs)
    slope = sxy / sxx
    intercept = my - slope * mx
    residual = sum((points[x] - (intercept + slope * x)) ** 2 for x in xs)
    total = sum((points[x] - my) ** 2 for x in xs)
    return {
        "intercept": round(intercept, 3),
        "slope": round(slope, 3),
        "r_squared": round(1.0 - residual / total, 5) if total else 1.0,
        "na_domain": [xs[0], xs[-1]],
        "points": n,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--arch", nargs="+",
                        default=[agx_crossarch.LOCAL_ARCH,
                                 agx_crossarch.RANKED_ARCH])
    # `metal-tt` runs one process per kernel per architecture, so the AGX
    # witness is restricted to the entry form a scored rows=2 kernel would
    # actually launch. The `f549` form exists to reproduce a proxy grid and
    # only needs the proxy.
    parser.add_argument("--agx-form", nargs="+", default=["wide"])
    parser.add_argument("--out", type=pathlib.Path,
                        default=ARTIFACTS / "e221_register_probe.json")
    args = parser.parse_args()

    shipped_header = live_header()
    header = rows_parameterized(shipped_header)
    plan = arms()
    parts = [PREAMBLE, header]
    for _, form, na, rows, table in plan:
        parts.append(entry(form, na, rows, table)[1])
    source = "\n".join(parts) + "\n"
    control_source = shipped_source(shipped_header)

    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        workdir = pathlib.Path(tmp)
        metal = workdir / "probe.metal"
        metal.write_text(source)
        control_metal = workdir / "shipped.metal"
        control_metal.write_text(control_source)
        (ARTIFACTS / "e221_probe.metal").write_text(source)
        (ARTIFACTS / "e221_shipped_control.metal").write_text(control_source)

        air = air_peaks(metal, workdir)
        shipped_air = air_peaks(control_metal, workdir / "shipped")
        lib = agx_crossarch.build_metallib(source, workdir / "lib")
        control_lib = agx_crossarch.build_metallib(
            control_source, workdir / "control_lib")
        wanted = tuple(f"{form}_" for form in args.agx_form)
        agx, shipped_agx = {}, {}
        for arch in args.arch:
            for target, source_lib, tag, select in (
                (agx, lib, f"tt_{arch}",
                 lambda name: name.startswith(wanted)),
                (shipped_agx, control_lib, f"tt_ship_{arch}", None),
            ):
                out = workdir / tag
                out.mkdir(parents=True, exist_ok=True)
                target[arch] = agx_crossarch.translate(
                    source_lib, arch, out, select=select)

    def proxy(na: int, rows: int, table: bool) -> int | None:
        want = instantiation_symbol(na, rows, table)
        for name, value in air.items():
            if name.startswith(want):
                return value
        return None

    rows_out = []
    for name, form, na, rows, table in plan:
        record = {
            "kernel": name, "form": form, "na": na, "rows": rows,
            "table": table,
            "accumulators": rows * na,
            # Per output row per k-block. Weights and metadata are invariant in
            # rows; activation and chunk sums are divided by it.
            "bytes_per_row_per_kblock": 12 + (36 if table else 32) * na / rows,
            "air_lane_peak": proxy(na, rows, table),
            "finding_549": F549.get(rows, {}).get(na),
            "finding_552_miscompiled": (form, na, rows, table) in MISCOMPILED,
        }
        for arch, found in agx.items():
            got = found.get(name, {})
            record[f"{arch}_registers"] = got.get("registers")
            record[f"{arch}_spill_bytes"] = got.get("spill_bytes")
            record[f"{arch}_text_bytes"] = got.get("text_bytes")
        rows_out.append(record)

    def shipped_proxy(na: int, table: bool) -> int | None:
        want = (f"_Z18qwen_e120_qmv_wideILi{na}ELb{1 if table else 0}EE")
        for name, value in shipped_air.items():
            if name.startswith(want):
                return value
        return None

    # Control: the plain rows=4 instantiation must reproduce the published grid.
    control = {}
    for na, want in F549_ROWS4.items():
        got = proxy(na, 4, False)
        control[na] = {"published": want, "measured": got,
                       "agrees": got == want}
    control_pass = all(v["agrees"] for v in control.values())

    # Control: the ROWS template parameter must not change the rows=4 body.
    parameterization = {}
    for na in NAS:
        for table in (False, True):
            key = f"na{na}/{'tbl' if table else 'plain'}"
            row = {
                "shipped_air_lane_peak": shipped_proxy(na, table),
                "parameterized_rows4_air_lane_peak": proxy(na, 4, table),
            }
            for arch in args.arch:
                suffix = "tbl" if table else "plain"
                row[f"shipped_{arch}_registers"] = (
                    shipped_agx[arch]
                    .get(f"ship_na{na}_{suffix}", {}).get("registers"))
                row[f"parameterized_rows4_{arch}_registers"] = (
                    agx[arch]
                    .get(f"f549_r4_na{na}_{suffix}", {}).get("registers"))
            row["air_agrees"] = (
                row["shipped_air_lane_peak"]
                == row["parameterized_rows4_air_lane_peak"])
            parameterization[key] = row
    parameterization_pass = all(
        v["air_agrees"] for v in parameterization.values())

    fits = {}
    for table in (False, True):
        suffix = "tbl" if table else "plain"
        for rows in ROWS:
            for label, domain in (("na5_9", range(5, 10)), ("na2_9", NAS)):
                witnesses = {
                    "air_lane_peak": {
                        na: proxy(na, rows, table) for na in domain
                        if proxy(na, rows, table)},
                }
                for form in ("f549", "wide"):
                    for arch in args.arch:
                        witnesses[f"{form}/{arch}_registers"] = {
                            na: agx[arch][f"{form}_r{rows}_na{na}_{suffix}"][
                                "registers"]
                            for na in domain
                            if agx[arch]
                            .get(f"{form}_r{rows}_na{na}_{suffix}", {})
                            .get("registers")}
                for witness, points in witnesses.items():
                    got = fit(points)
                    if got:
                        fits[f"{suffix}/rows{rows}/{witness}/{label}"] = got

    report = {
        "probe": "e221-register-probe",
        "step": 0,
        "harness": "static",
        "gpu_seconds": 0,
        "official_or_ranked_score": False,
        "gate_qualified_for_timing": False,
        "source_sha256": hashlib.sha256(source.encode()).hexdigest(),
        "qwen35_swift_sha256": hashlib.sha256(
            QWEN35.read_bytes()).hexdigest(),
        "base_sha": subprocess.run(
            ["git", "-C", str(REPO), "rev-parse", "HEAD"],
            capture_output=True, text=True).stdout.strip(),
        "worktree_dirty": bool(subprocess.run(
            ["git", "-C", str(REPO), "status", "--porcelain"],
            capture_output=True, text=True).stdout.strip()),
        "arches": list(args.arch),
        "finding_549_rows4_control": control,
        "finding_549_rows4_control_pass": control_pass,
        "rows_parameterization_control": parameterization,
        "rows_parameterization_control_pass": parameterization_pass,
        "finding_574_rows4_fit": {"intercept": F574_ROWS4_FIT[0],
                                  "slope": F574_ROWS4_FIT[1]},
        "finding_574_rows2_predicted_slope": F574_ROWS2_SLOPE,
        "finding_574_rows2_na5_bracket": list(F574_ROWS2_NA5_BRACKET),
        "finding_549_air_boundary": F549_BOUNDARY,
        "fits": fits,
        "kernels": rows_out,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(f"e221: wrote {args.out}")
    print(f"e221: FINDING 549 rows=4 control "
          f"{'PASS' if control_pass else 'FAIL'}")
    for na in sorted(F549_ROWS4):
        got = control[na]
        print(f"  NA={na}: published {got['published']} measured "
              f"{got['measured']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
