#!/usr/bin/env python3
"""E42 - inject a bit-exact, width-gated regression into the affine4/g64 QMV cells.

Why this exists
---------------
psi (the quantised-matvec share of the candidate leg) has never been measured.
Every attempt failed the same way: the effect of interest is ~0.06 % against a
paired-E2E floor of 0.417 % normal / 0.632 % exact at n=4 (`research/e39_mde.py`).
So E42 does not measure an improvement. It injects a large, *deliberate*
slowdown whose kernel-level magnitude is measured on the shapes-only curve, and
divides:

    psi_effective = (measured leg slowdown) / (measured kernel slowdown)

Bit-exactness by construction, not by luck
------------------------------------------
The perturbation runs the *entire* accumulation region `E42_PASSES` extra times.
Each pass re-initialises the accumulators and then executes the unchanged K loop
in the unchanged order, so the accumulators after the final pass hold exactly the
bits the base kernel would have held. Nothing is reassociated, no lane
membership moves, `simd_sum` and the store are untouched, and the write happens
once, after the last pass. Compare the alternatives that were rejected: `+ 0.0f *`
does not survive fast-math, and any partial/fused second pass changes the FP
expression tree - reassociation on the verify path is a ranked-measured
rejection class (`research/crossrow-closure.md:31-38`).

Because the earlier passes are dead by construction, a compiler is *entitled* to
delete them. That is a measurement risk, not a correctness risk, and it is
checked two ways before any leg is timed: statically with
`research/e42_air_probe.metal` + `research/air_kernel_stats.py` (device_loads and
float_ops must scale with the pass count), and dynamically on the shapes-only
curve (the treated widths must actually slow down).

NOTHING HERE SHIPS. Every arm is a regression; the branch ends with the two
twins byte-identical to BASE_SHA.

Usage
-----
    research/e42_perturb.py --arm p2 --level 1     # patch worktree, twins locked
    research/e42_perturb.py --arm p6 --level 2
    research/e42_perturb.py --arm m1 --level 1
    research/e42_perturb.py --revert               # restore both twins from base
    research/e42_perturb.py --self-test            # no worktree writes
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HDR = ROOT / "Vendor/mlx-swift/Source/Cmlx/mlx/mlx/backend/metal/kernels/quantized.h"
TWIN = ROOT / "Vendor/mlx-swift/Source/Cmlx/mlx-generated/quantized.cpp"
# .h line N is .cpp line N+13; the generated twin is the header wrapped in a raw
# string literal, so the twin is regenerated by splice and can never drift.
TWIN_OFFSET = 13

PASS_COMMENT = """  // E42 (research-only, never submitted): re-run the whole accumulation
  // region E42_PASSES extra times. Every pass re-initialises the accumulators
  // and repeats the unchanged K loop in the unchanged order, so the surviving
  // final pass is bit-identical to the base kernel by construction.
"""

# (anchor, replacement) pairs applied in order. Anchors are unique in the file.
STRUCT_EDITS = [
    # --- pair kernel (M == 2 in the >= 4096 tier, all widths in the lower tier)
    (
        "template <typename T, int M>\nMETAL_FUNC void qmv_fast_crossrow_affine4_g64(",
        # E42_ROWS_PER_GROUP_ECHO is unused by the kernel. CrossrowGate in
        # Tests/MLXFastTests/QwenQMVCostCurveTests.swift reads inputs_per_group
        # out of the third template argument of the instantiation text, so
        # without this echo every patched pair-kernel row in the cost curve
        # would report ipg = the pass level.
        "template <typename T, int M, int E42_ROWS_PER_GROUP_ECHO = 2, int E42_PASSES = 0>\n"
        "METAL_FUNC void qmv_fast_crossrow_affine4_g64(",
    ),
    (
        """  thread float single_result[rows_per_simd];
  for (int r = 0; r < rows_per_simd; r++) {
    pair_result[r] = 0.0f;
    single_result[r] = 0.0f;
  }

  for (int k = 0; k < in_vec_size; k += block_size) {""",
        """  thread float single_result[rows_per_simd];
"""
        + PASS_COMMENT
        + """  for (int e42_pass = 0; e42_pass <= E42_PASSES; e42_pass++) {
  for (int r = 0; r < rows_per_simd; r++) {
    pair_result[r] = 0.0f;
    single_result[r] = 0.0f;
  }

  for (int k = 0; k < in_vec_size; k += block_size) {""",
    ),
    (
        """        single_result[r] += qdot_affine4_loaded<float>(
            packed[r], x0, scale_local[r], bias_local[r], sum0);
      }
    }
  }

  if (has_pair) {""",
        """        single_result[r] += qdot_affine4_loaded<float>(
            packed[r], x0, scale_local[r], bias_local[r], sum0);
      }
    }
  }
  }

  if (has_pair) {""",
    ),
    # --- wide/NA kernel (M >= 3 in the >= 4096 tier)
    (
        "template <typename T, int NA, bool DIRECT_NIBBLES = false>\nMETAL_FUNC void qmv_fast_crossrow_affine4_g64_wide(",
        "template <typename T, int NA, bool DIRECT_NIBBLES = false, int E42_PASSES = 0>\nMETAL_FUNC void qmv_fast_crossrow_affine4_g64_wide(",
    ),
    (
        """  VF acc[rows_per_simd];
  for (int r = 0; r < rows_per_simd; r++) {
    acc[r] = VF(0.0f);
  }
""",
        """  VF acc[rows_per_simd];
"""
        + PASS_COMMENT
        + """  for (int e42_pass = 0; e42_pass <= E42_PASSES; e42_pass++) {
  for (int r = 0; r < rows_per_simd; r++) {
    acc[r] = VF(0.0f);
  }
""",
    ),
    (
        """    for (int r = 0; r < rows_per_simd; r++) {
      acc[r] += scale_local[r] * partial[r] + sums * bias_local[r];
    }
  }

  for (int r = 0; r < rows_per_simd; r++) {
    for (int m = 0; m < NA; m++) {
      const float reduced = simd_sum(acc[r][m]);""",
        """    for (int r = 0; r < rows_per_simd; r++) {
      acc[r] += scale_local[r] * partial[r] + sums * bias_local[r];
    }
  }
  }

  for (int r = 0; r < rows_per_simd; r++) {
    for (int m = 0; m < NA; m++) {
      const float reduced = simd_sum(acc[r][m]);""",
    ),
    # --- the M/IPG wrapper forwards the level to both wide instantiations
    (
        "template <typename T, int M, int IPG, bool DIRECT_NIBBLES = false>\nMETAL_FUNC void qmv_fast_crossrow_affine4_g64_m(",
        "template <typename T, int M, int IPG, bool DIRECT_NIBBLES = false, int E42_PASSES = 0>\nMETAL_FUNC void qmv_fast_crossrow_affine4_g64_m(",
    ),
    (
        """  if (TAIL == 0 || M - first_m >= IPG) {
    qmv_fast_crossrow_affine4_g64_wide<T, IPG, DIRECT_NIBBLES>(
        w, scales, biases, x, y, in_vec_size, out_vec_size,
        first_m, out_row, simd_lid);
  } else {
    qmv_fast_crossrow_affine4_g64_wide<
        T, (TAIL >= 2 ? TAIL : 2), DIRECT_NIBBLES>(""",
        """  if (TAIL == 0 || M - first_m >= IPG) {
    qmv_fast_crossrow_affine4_g64_wide<T, IPG, DIRECT_NIBBLES, E42_PASSES>(
        w, scales, biases, x, y, in_vec_size, out_vec_size,
        first_m, out_row, simd_lid);
  } else {
    qmv_fast_crossrow_affine4_g64_wide<
        T, (TAIL >= 2 ? TAIL : 2), DIRECT_NIBBLES, E42_PASSES>(""",
    ),
]

# The single-row (M == 1) fallthrough cell. Its K loop walks the pointers, so a
# repeat pass has to restore them; the base pointers are captured before the
# first pass and re-installed at the top of every pass.
M1_EDITS = [
    (
        "template <typename T, int group_size, int bits>\nMETAL_FUNC void qmv_fast_impl(",
        "template <typename T, int group_size, int bits, int E42_PASSES = 0>\nMETAL_FUNC void qmv_fast_impl(",
    ),
    (
        """  x += tid.x * in_vec_size + simd_lid * values_per_thread;
  y += tid.x * out_vec_size + out_row;

  for (int k = 0; k < in_vec_size; k += block_size) {""",
        """  x += tid.x * in_vec_size + simd_lid * values_per_thread;
  y += tid.x * out_vec_size + out_row;
"""
        + PASS_COMMENT
        + """  const device uint8_t* const e42_ws0 = ws;
  const device T* const e42_scales0 = scales;
  const device T* const e42_biases0 = biases;
  const device T* const e42_x0 = x;
  for (int e42_pass = 0; e42_pass <= E42_PASSES; e42_pass++) {
  ws = e42_ws0;
  scales = e42_scales0;
  biases = e42_biases0;
  x = e42_x0;
  for (int row = 0; row < results_per_simdgroup; row++) {
    result[row] = 0;
  }

  for (int k = 0; k < in_vec_size; k += block_size) {""",
    ),
    (
        """    x += block_size;
  }

  for (int row = 0; row < results_per_simdgroup; row++) {
    result[row] = simd_sum(result[row]);""",
        """    x += block_size;
  }
  }

  for (int row = 0; row < results_per_simdgroup; row++) {
    result[row] = simd_sum(result[row]);""",
    ),
    (
        """        default:
          break;
      }
    }
  }
  qmv_fast_impl<T, group_size, bits>(
      w,
      scales,
      biases,
      x,
      y,
      in_vec_size,
      out_vec_size,
      tid,
      simd_gid,
      simd_lid);
}""",
        """        default:
          break;
      }
    }
  }
  if (ntg.x == 1) {
    qmv_fast_impl<T, group_size, bits, E42_M1_PASSES>(
        w, scales, biases, x, y, in_vec_size, out_vec_size,
        tid, simd_gid, simd_lid);
    return;
  }
  qmv_fast_impl<T, group_size, bits>(
      w,
      scales,
      biases,
      x,
      y,
      in_vec_size,
      out_vec_size,
      tid,
      simd_gid,
      simd_lid);
}""",
    ),
]

# Dispatch table anchors, per width, for both out_vec_size tiers. The tiers share
# the `case 2:` body verbatim, so the >= 4096 anchor carries its preceding comment
# to stay unique. No scored shape lives in the 1024..4096 tier, but treating it
# too makes the gate exactly "every affine4/g64 fast-QMV dispatch at this width"
# with no shape carve-out to caveat.
IPG = {3: 3, 4: 4, 5: 5, 6: 3, 7: 4, 8: 4, 9: 5}
LVL = "@LVL@"
# Stripped in the anchor, ", 2" in the replacement: see E42_ROWS_PER_GROUP_ECHO.
ECHO = "@ECHO@"
HI_CASE2 = """      // promoted pair kernel is kept there byte-for-byte.
      switch (ntg.x) {
        case 2:
          qmv_fast_crossrow_affine4_g64<T, 2@ECHO@@LVL@>("""
CASE_REPLACEMENTS = {2: HI_CASE2}
for _w, _ipg in IPG.items():
    CASE_REPLACEMENTS[_w] = f"qmv_fast_crossrow_affine4_g64_m<T, {_w}, {_ipg}, true@LVL@>("
LO_CASE_REPLACEMENTS = {2: None}
for _w in range(3, 10):
    LO_CASE_REPLACEMENTS[_w] = f"qmv_fast_crossrow_affine4_g64<T, {_w}@ECHO@@LVL@>("


def _strip_markers(text: str) -> str:
    return text.replace(LVL, "").replace(ECHO, "")


CASE_ANCHORS = {w: _strip_markers(t) for w, t in CASE_REPLACEMENTS.items()}
LO_CASE_ANCHORS = {w: (_strip_markers(t) if t else None) for w, t in LO_CASE_REPLACEMENTS.items()}

ARMS = {
    "p2": range(2, 10),
    "p6": range(6, 10),
    # M=6 alone. Ranked telemetry cannot separate a step at M>=6 from a plain
    # quadratic in M, and the two disagree by 4.4x on T(6)-T(5); a single-width
    # injection prices that boundary causally instead of inferring a mixture.
    "m6": range(6, 7),
    "m1": range(0, 0),
}


def base_header(base_sha: str) -> str:
    rel = HDR.relative_to(ROOT).as_posix()
    return subprocess.run(
        ["git", "show", f"{base_sha}:{rel}"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def apply_edits(text: str, edits) -> str:
    for anchor, replacement in edits:
        if text.count(anchor) != 1:
            raise SystemExit(
                f"e42_perturb: anchor matched {text.count(anchor)} times, expected 1:\n"
                f"{anchor[:120]}..."
            )
        text = text.replace(anchor, replacement)
    return text


def build_arm(base_text: str, arm: str, level: int) -> str:
    if arm not in ARMS:
        raise SystemExit(f"e42_perturb: unknown arm {arm}")
    text = apply_edits(base_text, STRUCT_EDITS)
    lvl = f", {level}"
    # >= 4096 tier first: it disambiguates the shared `case 2:` body for the
    # 1024..4096 tier, whose plain anchor only becomes unique afterwards.
    for table_a, table_r in ((CASE_ANCHORS, CASE_REPLACEMENTS), (LO_CASE_ANCHORS, LO_CASE_REPLACEMENTS)):
        for width in ARMS[arm]:
            anchor = table_a[width]
            if anchor is None:
                anchor = CASE_ANCHORS[2].split("\n")[-1]
                replacement = CASE_REPLACEMENTS[2].split("\n")[-1]
            else:
                replacement = table_r[width]
            replacement = replacement.replace(ECHO, ", 2").replace(LVL, lvl)
            if text.count(anchor) != 1:
                raise SystemExit(
                    f"e42_perturb: width {width} anchor matched {text.count(anchor)} times: {anchor[:80]!r}"
                )
            text = text.replace(anchor, replacement)
    if arm == "m1":
        text = apply_edits(text, M1_EDITS)
        text = text.replace("E42_M1_PASSES", str(level))
    return text


def write_twins(header_text: str) -> None:
    """Splice the new header into the twin. Must be called with pristine twins."""
    twin_lines = TWIN.read_text().splitlines(keepends=True)
    n_h = len(HDR.read_text().splitlines())
    head, tail = twin_lines[:TWIN_OFFSET], twin_lines[TWIN_OFFSET + n_h :]
    HDR.write_text(header_text)
    TWIN.write_text("".join(head) + header_text + "".join(tail))
    verify_lockstep()


def verify_lockstep() -> None:
    h = HDR.read_text().splitlines()
    c = TWIN.read_text().splitlines()
    window = c[TWIN_OFFSET : TWIN_OFFSET + len(h)]
    if window != h:
        for i, (a, b) in enumerate(zip(h, window)):
            if a != b:
                raise SystemExit(f"e42_perturb: twin drift at .h:{i + 1}: {a!r} != {b!r}")
        raise SystemExit("e42_perturb: twin length mismatch")
    tail = c[TWIN_OFFSET + len(h) :]
    if ")preamble\";" not in tail or tail.index(")preamble\";") != 2:
        raise SystemExit(f"e42_perturb: unexpected twin tail {tail[:4]}")
    print(f"e42_perturb: twin lockstep OK (.h {len(h)} lines == .cpp[{TWIN_OFFSET + 1}..])")


def revert(base_sha: str) -> None:
    subprocess.run(
        ["git", "checkout", base_sha, "--", HDR.relative_to(ROOT).as_posix(), TWIN.relative_to(ROOT).as_posix()],
        cwd=ROOT,
        check=True,
    )
    verify_lockstep()


def self_test(base_sha: str) -> None:
    base = base_header(base_sha)
    checks = 0
    structural = apply_edits(base, STRUCT_EDITS)
    for arm, level in [
        ("p2", 1),
        ("p2", 2),
        ("p6", 1),
        ("p6", 2),
        ("m6", 2),
        ("m1", 1),
    ]:
        text = build_arm(base, arm, level)
        assert text != base, (arm, level)
        # the repeat loop exists once per treated kernel body (3rd is qmv_fast_impl)
        assert text.count("for (int e42_pass = 0; e42_pass <= E42_PASSES; e42_pass++)") == (
            3 if arm == "m1" else 2
        ), arm
        checks += 2
        def instantiate(template: str) -> str:
            return template.replace(ECHO, ", 2").replace(LVL, f", {level}")

        for w in range(2, 10):
            treated = w in ARMS[arm]
            # every treated width carries the level in BOTH out_vec tiers, and
            # every untreated width keeps its base instantiation verbatim
            hi = instantiate(CASE_REPLACEMENTS[w]) if treated else CASE_ANCHORS[w]
            assert hi in text, (arm, w, "hi")
            lo = LO_CASE_REPLACEMENTS[w]
            if lo is not None:
                lo = instantiate(lo) if treated else _strip_markers(lo)
                assert lo in text, (arm, w, "lo")
            if treated:
                assert CASE_ANCHORS[w] not in text, (arm, w, "residual base cell")
            checks += 2
        # CrossrowGate parses inputs_per_group out of template argument 3, so a
        # patched pair-kernel cell must still present a literal 2 there.
        for site in re.findall(r"qmv_fast_crossrow_affine4_g64<T, \d+[^>]*>", text):
            args = [a.strip() for a in site.split("<")[1].rstrip(">").split(",")]
            assert len(args) == 2 or args[2] == "2", (arm, site)
            checks += 1
        # the accumulation expression, the reduction and the store are untouched
        assert "const float reduced = simd_sum(acc[r][m]);" in text
        assert "acc[r] += scale_local[r] * partial[r] + sums * bias_local[r];" in text
        assert text.count("y[(first_m + m) * out_vec_size + out_row + r] =") == 1
        checks += 3
        # an arm differs from the structural (level-0) form only in the table
        struct_lines = structural.splitlines()
        arm_lines = text.splitlines()
        if arm != "m1":
            assert len(struct_lines) == len(arm_lines), arm
            diff = [i for i, (a, b) in enumerate(zip(struct_lines, arm_lines)) if a != b]
            assert len(diff) == 2 * len(list(ARMS[arm])), (arm, len(diff))
            checks += 2
    assert build_arm(base, "p6", 1) != build_arm(base, "p2", 1)
    assert build_arm(base, "m6", 2) != build_arm(base, "p6", 2)
    checks += 1
    print(f"E42 PERTURB SELF-TEST PASSED ({checks} checks)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", choices=sorted(ARMS))
    ap.add_argument("--level", type=int, default=1)
    ap.add_argument("--base-sha", default="04ad6bf11437c269df85a47e91faa769c74fe6da")
    ap.add_argument("--revert", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        self_test(args.base_sha)
        return 0
    if args.revert:
        revert(args.base_sha)
        print("e42_perturb: twins restored to base")
        return 0
    if not args.arm:
        ap.error("--arm is required unless --revert/--self-test")
    if args.level < 1:
        ap.error("--level must be >= 1 (level 0 is the base arm itself)")
    revert(args.base_sha)
    text = build_arm(base_header(args.base_sha), args.arm, args.level)
    write_twins(text)
    print(f"e42_perturb: arm={args.arm} level={args.level} twins patched and locked")
    return 0


if __name__ == "__main__":
    sys.exit(main())
