#!/usr/bin/env python3
"""Derive the E64 rung-0b arms FROM the shipped wide crossrow QMV kernel.

Rung 0b is a dose test run backwards: instead of removing the accumulator
`alloca` at NA=6, it ADDS one at NA=5, where the measured bandwidth ladder is
on-model. Three arms come out of this generator, and every one of them is the
shipped body plus a closed list of exact substitutions, so no arm can drift away
from what ships:

  plain    the shipped body, renamed. Control.
  forced   the shipped body with `acc` forced into private memory by a
           `volatile` qualifier. Storage moves; not one floating-point
           operation changes.
  ballast  the shipped body with 4*NA extra live registers carried across the k
           loop and NO alloca, so a reader can separate "the accumulator left
           the registers" from "the kernel holds more registers".

The ballast values come from `volatile` device loads and are consumed in a cold
block the compiler cannot prove is dead. Volatile is what stops the loads being
sunk past the k loop into that block, which is the only way the values stay live
across the loop without adding arithmetic to it.

  python3 research/e64_wide_gen.py            # write the generated header
  python3 research/e64_wide_gen.py --check    # verify it is still in sync
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

SHIPPED = pathlib.Path(
    "Vendor/mlx-swift/Source/Cmlx/mlx/mlx/backend/metal/kernels/quantized.h"
)
GENERATED = pathlib.Path("research/generated/e64_wide_arms.h")

TEMPLATE_LINE = "template <typename T, int NA, bool DIRECT_NIBBLES = false>"
SIGNATURE = "METAL_FUNC void qmv_fast_crossrow_affine4_g64_wide("
NA_ASSERT = (
    '  static_assert(NA >= 2 && NA <= 5, "wide multi-row QMV supports NA in [2, 5]");'
)
PROBE_ASSERT = '  static_assert(NA >= 2 && NA <= 9, "probe-only NA bound");'

ACC_DECL = "  VF acc[rows_per_simd];"
FORCED_ACC_DECL = """  // E64 forced arm: storage only. `volatile` denies the promotion of this
  // array to registers, so it stays in private memory. The expression that
  // updates it is untouched, so the emitted fadd/fmul sequence is unchanged.
  volatile thread VF acc[rows_per_simd];"""

ACC_UPDATE = (
    "      acc[r] += scale_local[r] * partial[r] + sums * bias_local[r];"
)
FORCED_ACC_UPDATE = """      // `a += b` spelled out, because a compound assignment on a volatile
      // vector is not portable Metal. The operation tree is identical.
      const VF acc_r = acc[r];
      acc[r] = acc_r + (scale_local[r] * partial[r] + sums * bias_local[r]);"""

ACC_READ = "      const float reduced = simd_sum(acc[r][m]);"
FORCED_ACC_READ = """      const VF acc_r = acc[r];
      const float reduced = simd_sum(acc_r[m]);"""

BALLAST_DECL = """  // E64 ballast arm: 4*NA extra values live across the k loop, no alloca, and
  // no arithmetic added inside the loop. The loads are volatile so they cannot
  // be sunk into the cold consumer below, which is what keeps them live.
  VF bal0, bal1, bal2, bal3;
  {
    const device volatile T* xb = reinterpret_cast<const device volatile T*>(x);
    for (int m = 0; m < NA; m++) {
      const int base = (first_m + m) * in_vec_size + int(simd_lid);
      bal0[m] = static_cast<float>(xb[base]);
      bal1[m] = static_cast<float>(xb[base + 32]);
      bal2[m] = static_cast<float>(xb[base + 64]);
      bal3[m] = static_cast<float>(xb[base + 96]);
    }
  }
"""

BALLAST_SINK = """  // Stores only, so the ballast adds no floating-point work. The condition
  // reads a bit pattern of the finished accumulator, for two reasons: it is not
  // loop-invariant, so the compiler cannot unswitch or hoist this block above
  // the k loop and let the ballast die early; and it is a signalling-NaN
  // pattern this kernel cannot produce from finite affine inputs. A guard on
  // `simd_lid` alone IS loop-invariant, and the compiler unswitched it.
  if (as_type<uint>(acc[0][0]) == 0xdeadbeefu) {
    for (int m = 0; m < NA; m++) {
      y[m] = static_cast<T>(bal0[m]);
      y[m + NA] = static_cast<T>(bal1[m]);
      y[m + 2 * NA] = static_cast<T>(bal2[m]);
      y[m + 3 * NA] = static_cast<T>(bal3[m]);
    }
  }
"""

EPILOGUE_ANCHOR = """  for (int r = 0; r < rows_per_simd; r++) {
    for (int m = 0; m < NA; m++) {"""

HEADER = """// GENERATED by research/e64_wide_gen.py -- do not edit by hand.
//
// Body extracted verbatim from {src} lines {lo}-{hi}
// (extracted-body sha256 {digest}), then rewritten per arm by exact
// substitutions that must each match once.
//
// Research only. Nothing here is on the scored path; the arms exist so one
// question can be answered at NA=5: does moving `acc` out of registers and into
// private memory, with identical arithmetic, reproduce the measured NA=5 -> 6
// bandwidth step?

#pragma once

"""


def rename(name: str) -> tuple[str, str]:
    return SIGNATURE, f"METAL_FUNC void qmv_fast_crossrow_affine4_g64_wide_{name}("


def arms() -> dict[str, list[tuple[str, str, str]]]:
    """arm -> [(why, exact old text, exact new text)], each matching once."""
    common = lambda name: [  # noqa: E731
        ("rename so the arm cannot shadow the shipped symbol", *rename(name)),
        ("relax the NA bound inside the probe only", NA_ASSERT, PROBE_ASSERT),
    ]
    return {
        "e64plain": common("e64plain"),
        "e64forced": common("e64forced")
        + [
            ("force `acc` into private memory", ACC_DECL, FORCED_ACC_DECL),
            ("volatile-safe accumulate, same operation tree",
             ACC_UPDATE, FORCED_ACC_UPDATE),
            ("volatile-safe readout", ACC_READ, FORCED_ACC_READ),
        ],
        "e64ballast": common("e64ballast")
        + [
            ("carry 4*NA extra live values across the k loop",
             ACC_DECL, ACC_DECL + "\n" + BALLAST_DECL),
            ("consume the ballast in a cold block",
             EPILOGUE_ANCHOR, BALLAST_SINK + EPILOGUE_ANCHOR),
        ],
    }


def extract(text: str) -> tuple[str, int, int]:
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if line.startswith(SIGNATURE):
            if lines[index - 1] != TEMPLATE_LINE:
                raise SystemExit(
                    f"{SHIPPED}: line {index}: expected {TEMPLATE_LINE!r}"
                )
            start = index - 1
            break
    if start is None:
        raise SystemExit(f"{SHIPPED}: no {SIGNATURE!r}")
    end = None
    for index in range(start, len(lines)):
        if lines[index] == "}":
            end = index
            break
    if end is None:
        raise SystemExit(f"{SHIPPED}: unterminated body from line {start + 1}")
    return "\n".join(lines[start:end + 1]) + "\n", start + 1, end + 1


def apply(body: str, rewrites: list[tuple[str, str, str]]) -> str:
    out = body
    for why, old, new in rewrites:
        if out.count(old) != 1:
            raise SystemExit(
                f"rewrite {why!r} matched {out.count(old)} times, expected 1"
            )
        out = out.replace(old, new)
    return out


def generate() -> str:
    body, lo, hi = extract(SHIPPED.read_text())
    digest = hashlib.sha256(body.encode()).hexdigest()
    parts = [HEADER.format(src=SHIPPED, lo=lo, hi=hi, digest=digest)]
    for name, rewrites in arms().items():
        parts.append(f"// --- arm {name} " + "-" * (58 - len(name)) + "\n//\n")
        for why, _, _ in rewrites:
            parts.append(f"//   {why}\n")
        parts.append("\n" + apply(body, rewrites) + "\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = generate()
    if args.check:
        if not GENERATED.exists() or GENERATED.read_text() != text:
            print(f"{GENERATED} is stale; rerun research/e64_wide_gen.py")
            return 1
        print(f"{GENERATED} is in sync with {SHIPPED}")
        return 0
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(text)
    print(f"{GENERATED} {len(text)} bytes, {len(arms())} arms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
