#!/usr/bin/env bash
# One E68 rung 3 end-to-end leg: select arm -> commit -> build -> measure ->
# unwind.
#
#   research/e68_run_leg.sh ARM TAG [--tokens N] [--hot] [--warmup]
#
# Modelled on research/e59_e2e_run.sh, with one structural difference. E59's
# arms rewrite a Metal source string that is JIT-compiled at run time, so its
# binary probe reads the arm back out of `__cstring`. An E68 arm is ordinary
# Swift that the optimiser compiles into the scheduler, so the witness is
# `__TEXT,__text`: every arm must produce a DIFFERENT text digest, and the
# `ship` arm must reproduce the tip's digest exactly. Both are recorded here
# and checked across the session.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
repo_root="${PWD}"

arm="${1:?usage: e68_run_leg.sh ARM TAG [--tokens N] [--hot] [--warmup]}"
tag="${2:?usage: e68_run_leg.sh ARM TAG [--tokens N] [--hot] [--warmup]}"
shift 2

tokens="${E68_TOKENS:-512}"
hot=0
warmup=0
while (($#)); do
  case "$1" in
    --tokens) tokens="$2"; shift 2 ;;
    --hot) hot=1; shift ;;
    # Declared in advance and excluded from the analysis. A cold first leg does
    # not cancel in a palindrome.
    --warmup) warmup=1; shift ;;
    *) echo "e68_run_leg: unknown argument $1" >&2; exit 2 ;;
  esac
done

readonly SCORED_FILES=(
  "Sources/MLXFastModel/Qwen36MTPBlockSession.swift"
)
# The two files that carry the wide multi-row QMV dispatch table. They are a
# SECOND factor, not a scored one: a 2x2 over {kernel table} x {depth price}
# has to move them per leg, and E75 submits neither of them.
readonly TABLE_FILES=(
  "Vendor/mlx-swift/Source/Cmlx/mlx/mlx/backend/metal/kernels/quantized.h"
  "Vendor/mlx-swift/Source/Cmlx/mlx-generated/quantized.cpp"
)
table_arm="${LEG_TABLE_ARM:-}"
table_arms_module="${LEG_TABLE_ARMS_MODULE:-research/e75_arms.py}"
prebuilt_cell="${LEG_PREBUILT_CELL:-}"
patched_files=("${SCORED_FILES[@]}")
if [[ -n "${table_arm}" ]]; then
  patched_files+=("${TABLE_FILES[@]}")
fi

base_sha="${E68_BASE_SHA:-$(git rev-parse origin/senpai/qwen38-mtp-r1)}"
root="${E68_E2E_ROOT:-${repo_root}/.mlxfast-private/e68-e2e}"
fixture="${E68_FIXTURE:-correctness_prompts/public_longcopy_gate_english_512_256.json}"
head_dir="${E68_HEAD_DIR:-${HOME}/.cache/mlxfast/qwen3.8-27b-mtp-v1/mtp-head-declared-run}"
rung1="${E68_RUNG1_CURVE:-research/e68-artifacts/e68-rung1.json}"
verify_forward_key="${E68_VERIFY_FORWARD_KEY:-}"

# Hooks a later experiment sets to reuse this runner unchanged. The defaults
# reproduce E68 exactly.
#   LEG_TIP_ARM     the arm whose generated bytes must equal the tip's, i.e.
#                   the arm the branch already ships. E68 shipped `ship`; a
#                   branch that banks a measured curve ships `pbfit`.
#   LEG_EXTRA_META  newline-separated `key=value` lines appended to meta.txt,
#                   for identity a later 2x2 needs and E68 did not have.
#   LEG_WANDB_LOGGER / LEG_WANDB_ARGS  the per-leg logger and its extra flags.
tip_arm="${LEG_TIP_ARM:-ship}"
wandb_logger="${LEG_WANDB_LOGGER:-research/e68_wandb_log.py}"
read -r -a wandb_args <<< "${LEG_WANDB_ARGS:-}"

# benchmark.sh derives the run lock from $HOME, which differs per role while the
# uid does not, so the default lock gives zero mutual exclusion against another
# student timing on the same box.
export MLXFAST_LOCAL_RUN_LOCK_DIR="${MLXFAST_LOCAL_RUN_LOCK_DIR:-/tmp/mlxfast-shared}"

# Ranked command-buffer geometry. See research/e59_e2e_run.sh for why
# DARKBLOOM_STARTUP_MEMORY_PROFILE is the lever that makes the other two
# exports survive on a 48 GiB host.
export DARKBLOOM_STARTUP_MEMORY_PROFILE="${DARKBLOOM_STARTUP_MEMORY_PROFILE:-full}"
export MLX_MAX_MB_PER_BUFFER="${MLX_MAX_MB_PER_BUFFER:-512}"
export MLX_MAX_OPS_PER_BUFFER="${MLX_MAX_OPS_PER_BUFFER:-50}"

pre_patch_sha="$(git rev-parse HEAD)"
transient_sha=""

unwind() {
  if [[ -n "${transient_sha}" ]]; then
    if [[ "$(git rev-parse HEAD)" == "${transient_sha}" ]]; then
      git reset -q "${pre_patch_sha}"
    else
      echo "e68_run_leg: HEAD moved during the leg; restoring files only" >&2
    fi
  fi
  git checkout -q "${pre_patch_sha}" -- "${patched_files[@]}" 2>/dev/null || true
}
trap unwind EXIT
trap 'exit 143' TERM
trap 'exit 130' INT

if [[ -n "$(git status --porcelain)" ]]; then
  echo "e68_run_leg: worktree is dirty; refusing to time over uncommitted work" >&2
  exit 1
fi
[[ -s "${fixture}" ]] || { echo "e68_run_leg: missing fixture ${fixture}" >&2; exit 2; }
[[ -s "${head_dir}/config.json" && -s "${head_dir}/model.safetensors" ]] \
  || { echo "e68_run_leg: declared head tree missing at ${head_dir}" >&2; exit 2; }

out="${root}/runs/${tag}"
rm -rf "${out}"; mkdir -p "${out}/reports"

macmon_bin="${MLXFAST_MACMON_BIN:-}"
if [[ -z "${macmon_bin}" ]]; then
  macmon_bin="$(command -v macmon 2>/dev/null || true)"
fi
[[ -n "${macmon_bin}" ]] || macmon_bin="${HOME}/bin/macmon"
gpu_temp() {
  [[ -x "${macmon_bin}" ]] || { echo ""; return 0; }
  "${macmon_bin}" pipe -s1 2>/dev/null | jq -r '.temp.gpu_temp_avg // empty'
}

# --- who else is on this GPU --------------------------------------------------
gate_json="${out}/gpu-gate.json"
python3 research/e49_gpu_gate.py --samples 5 --out "${gate_json}"
case "$?" in
  0) echo "e68_run_leg: GPU gate idle" >&2 ;;
  1) echo "e68_run_leg: GPU gate reports BUSY; not timing." >&2; exit 3 ;;
  *) echo "e68_run_leg: GPU utilization counter unavailable; not timing blind." >&2; exit 4 ;;
esac

# --- select the kernel dispatch table -----------------------------------------
# The table arm module refuses to write a table whose bytes do not hash to the
# source it claims to reproduce, so a mislabelled leg fails here rather than at
# the 40C gate.
if [[ -n "${table_arm}" ]]; then
  python3 "${table_arms_module}" "${table_arm}" --out "${out}/table-arm.json" \
    > "${out}/table-arm.log" 2>&1 || {
    echo "e68_run_leg: table arm ${table_arm} failed" >&2
    cat "${out}/table-arm.log" >&2
    exit 2
  }
fi

# --- select the arm -----------------------------------------------------------
arm_args=("${arm}" --out "${out}/arm.json")
if [[ "${arm}" == "pbfit" ]]; then
  [[ -s "${rung1}" ]] || {
    echo "e68_run_leg: pbfit needs the rung-1 curve at ${rung1}" >&2; exit 2; }
  arm_args+=(--raw-from "${rung1}")
  [[ -n "${verify_forward_key}" ]] \
    && arm_args+=(--verify-forward-key "${verify_forward_key}")
fi
python3 research/e68_swift_arm.py "${arm_args[@]}" > "${out}/arm.log" 2>&1 || {
  echo "e68_run_leg: arm selection failed for ${arm}" >&2
  cat "${out}/arm.log" >&2
  exit 2
}

# The selector edits one line. Prove it took before spending a build, and
# prove no other arm's selector survived in the file.
selected="$(grep -c "let depthPriceArm: DepthPriceArm = .${arm}$" \
  "${SCORED_FILES[0]}")"
total_selectors="$(grep -c "let depthPriceArm: DepthPriceArm = " \
  "${SCORED_FILES[0]}")"
if ((selected != 1 || total_selectors != 1)); then
  echo "e68_run_leg: selector says ${selected}/${total_selectors} for ${arm}" >&2
  exit 2
fi

# The `ship` arm must leave the tree byte-identical to the commit this leg
# started from, which already carries the depth-price patch at arm `ship`.
# Any diff means the selector rewrote something beyond its one line.
#
# Comparing against `base_sha` instead would be wrong and was: the E68 patch
# adds the price vectors to EVERY arm, so the `ship` file legitimately differs
# from the advisor branch by the whole patch. That check failed all three
# `ship` legs of the first rung-3 session and left the experiment with no
# control. Behavioural identity between `ship` and the tip is proven by
# QwenMTPDepthPriceTests, which compares cumulative cost bit for bit, the
# threshold expression, and the whole walk on a dense acceptance grid.
if [[ "${arm}" == "${tip_arm}" ]] \
   && ! git diff --quiet "${pre_patch_sha}" -- "${SCORED_FILES[@]}"; then
  echo "e68_run_leg: ${arm} arm differs from ${pre_patch_sha}; not a control" >&2
  git diff --stat "${pre_patch_sha}" -- "${SCORED_FILES[@]}" >&2
  exit 2
fi

git add -- "${patched_files[@]}"
git commit -q --allow-empty -m "E68 leg ${tag}: TRANSIENT ${arm} arm bytes under measurement

Unwound to ${pre_patch_sha} when the leg exits, including on a crash, so the
branch's scored surface stays byte-identical between legs. This commit exists
only so the bytes the compiler saw are reachable while the leg runs."
transient_sha="$(git rev-parse HEAD)"

# --- build both roots, or install a cell built before the session -------------
# A 2x2 that switches the kernel table per leg would otherwise recompile Cmlx
# and the metallib mid-session. LEG_PREBUILT_CELL installs binaries built from
# these exact bytes before any timing started; the source digests must match,
# and meta.txt records the installed binary's own digests, so the swap cannot
# put an unrelated build under measurement.
status=0
if [[ -n "${prebuilt_cell}" ]]; then
  research/e75_rungD_install_cell.sh "${prebuilt_cell}" \
    > "${out}/install-cell.log" 2>&1 || status=1
  ((status == 0)) || {
    echo "e68_run_leg: installing prebuilt cell ${prebuilt_cell} failed" >&2
    tail -20 "${out}/install-cell.log" >&2
    exit 5
  }
else
  mkdir -p .build/clang-module-cache .build-worker/clang-module-cache
  CLANG_MODULE_CACHE_PATH="${PWD}/.build/clang-module-cache" \
    swift build -c release --force-resolved-versions --product mlxfast-swift \
    > "${out}/build-cli.log" 2>&1 || status=1
  CLANG_MODULE_CACHE_PATH="${PWD}/.build-worker/clang-module-cache" \
    swift build -c release --force-resolved-versions \
    --scratch-path .build-worker --product mlxfast-runtime-worker \
    > "${out}/build-worker.log" 2>&1 || status=1
  ((status == 0)) || {
    echo "e68_run_leg: build failed for ${arm}" >&2
    grep -m5 'error:' "${out}/build-worker.log" >&2
    exit 5
  }
fi

# The selector must still read the same arm after the build, so a stale or
# concurrently restored file cannot be timed under the wrong label.
post_selected="$(grep -c "let depthPriceArm: DepthPriceArm = .${arm}$" \
  "${SCORED_FILES[0]}")"
((post_selected == 1)) || {
  echo "e68_run_leg: selector changed during the build" >&2; exit 5; }

# --- measure ------------------------------------------------------------------
{
  echo "tag=${tag}"
  echo "arm=${arm}"
  echo "base_sha=${base_sha}"
  echo "measured_commit_unwound=${transient_sha}"
  echo "branch_commit=${pre_patch_sha}"
  echo "dirty=$(git status --porcelain | wc -l | tr -d ' ')"
  echo "tokens=${tokens}"
  echo "offered_depth=${MLXFAST_QWEN_MTP_DEPTH:-8}"
  echo "fixture=${fixture}"
  echo "fixture_sha256=$(shasum -a 256 "${fixture}" | cut -d' ' -f1)"
  echo "head_dir=${head_dir}"
  echo "head_safetensors_sha256=$(shasum -a 256 "${head_dir}/model.safetensors" | cut -d' ' -f1)"
  echo "head_run_dir_tree_sha256=$(python3 research/e59_head_tree_digest.py "${head_dir}")"
  echo "scored_source_sha256=$(shasum -a 256 "${SCORED_FILES[@]}" | awk '{printf "%s ", $1}')"
  echo "cli_sha256=$(shasum -a 256 .build/release/mlxfast-swift | cut -d' ' -f1)"
  echo "worker_sha256=$(shasum -a 256 .build-worker/release/mlxfast-runtime-worker | cut -d' ' -f1)"
  # The arm witness. A Swift arm changes compiled code, so `__text` must differ
  # between arms and must match the tip for `ship`. The whole-file digest also
  # moves with LC_UUID and the signature slots, so it cannot do this job.
  echo "worker_text_sha256=$(python3 research/e59_worker_digest.py \
    .build-worker/release/mlxfast-runtime-worker --json \
    | python3 -c 'import json,sys;print(json.load(sys.stdin)["sections"]["__TEXT,__text"]["sha256"])')"
  # The kernel table is a JIT source string compiled into the binary, so it
  # witnesses in `__cstring` while the Swift depth price witnesses in `__text`.
  # A 2x2 must show two distinct values on each axis and four distinct pairs.
  echo "worker_cstring_sha256=$(python3 research/e59_worker_digest.py \
    .build-worker/release/mlxfast-runtime-worker --json \
    | python3 -c 'import json,sys;print(json.load(sys.stdin)["sections"]["__TEXT,__cstring"]["sha256"])')"
  echo "prebuilt_cell=${prebuilt_cell##*/}"
  echo "kernel_table_arm=${table_arm}"
  echo "kernel_table_sha256=$(shasum -a 256 "${TABLE_FILES[@]}" | awk '{printf "%s ", $1}')"
  echo "metallib_sha256=$(shasum -a 256 .build-worker/release/mlx.metallib | cut -d' ' -f1)"
  echo "metallib_source_fingerprint=$(tools/build-mlx-metallib.sh --print-fingerprint)"
  echo "metallib_published_fingerprint=$(awk '{print $2}' \
    .build-worker/release/mlx.metallib.fingerprint)"
  echo "cool_gate_requested=$((1 - hot))"
  echo "cool_gate_passed_real_gate=$( ((hot)) && echo false || echo true )"
  echo "gate_qualified_for_timing=$( ((hot)) && echo false || echo true )"
  echo "startup_memory_profile=${DARKBLOOM_STARTUP_MEMORY_PROFILE}"
  echo "mlx_max_mb_per_buffer=${MLX_MAX_MB_PER_BUFFER}"
  echo "mlx_max_ops_per_buffer=${MLX_MAX_OPS_PER_BUFFER}"
  echo "physical_memory_gib=$(( $(sysctl -n hw.memsize) >> 30 ))"
  echo "wired_residency_active=$(
    if [[ "${DARKBLOOM_QWEN_MTP_WIRED_ZH:-}" != "0" ]] \
      && (( $(sysctl -n hw.memsize) >= (96 << 30) )); then
      echo true
    else
      echo false
    fi)"
  echo "gpu_temp_entry_c=$(gpu_temp)"
  echo "started=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  [[ -n "${LEG_EXTRA_META:-}" ]] && printf '%s\n' "${LEG_EXTRA_META}"
} > "${out}/meta.txt"

export MLXFAST_QWEN_MTP_HEAD_DIR="${head_dir}"
export MLXFAST_QWEN_MTP_LOCAL_GOLDEN_FIXTURE="${fixture}"
export MLXFAST_QWEN_MTP_LOCAL_ITERATE_TOKENS="${tokens}"
export MLXFAST_SCORE_PATH="${out}/score.json"
export MLXFAST_CAPTURE_REAL_BIN="${repo_root}/.build/release/mlxfast-swift"
export MLXFAST_SWIFT_BIN="${repo_root}/research/capture-cli.sh"
export MLXFAST_CAPTURE_DIR="${out}/reports"
((hot)) && export MLXFAST_LOCAL_COOL_GATE=0

./benchmark-qwen-mtp.sh --local-iterate > "${out}/run.log" 2>&1
rc=$?

{
  echo "gpu_temp_exit_c=$(gpu_temp)"
  echo "wrapper_exit=${rc}"
  echo "finished=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} >> "${out}/meta.txt"

stale_metal="$(grep -c 'built from different vendored Metal sources' "${out}/run.log")"
echo "stale_metallib_warnings=${stale_metal}" >> "${out}/meta.txt"
if ((stale_metal > 0)); then
  echo "e68_run_leg: ${tag} saw ${stale_metal} stale-metallib warnings; discarding the leg" >&2
  rc=6
fi

echo "warmup_discarded=${warmup}" >> "${out}/meta.txt"
echo "status=${rc}" >> "${out}/meta.txt"

# Log while measuring, never once at session end: a session that dies on leg 4
# must still leave legs 1-3 on the board.
if ((rc == 0)); then
  python3 "${wandb_logger}" --leg "${out}" ${wandb_args[@]+"${wandb_args[@]}"} \
    >> "${out}/wandb.log" 2>&1 \
    || echo "e68_run_leg: W&B logging failed for ${tag}; see ${out}/wandb.log" >&2
fi

exit "${rc}"
