#!/usr/bin/env bash
# E78 rung 1: exactness of the width-dependent inner-group count.
#
#   research/e78_rung1.sh [--golden-only|--ledgers-only]
#
# Two sessions, because the two phases need different leg runners:
#
#   1. one `a_ship` benchmark leg, which produces the reference rows every arm
#      is then judged against. Not timed, so it runs ungated.
#   2. four untimed 512-token depth-8 ledger legs -- the base arm, both hybrid
#      arms and the `c_perturb` positive control -- all replaying that one
#      golden, so a ledger difference between arms is a difference in the
#      kernel and not in the prompt or the schedule.
#
# The golden is generated by the candidate build, exactly as every local mode
# does. It therefore proves internal consistency against the base table on this
# host; it is NOT the organizer's hidden reference.
#
# The positive control runs in its own session because it is EXPECTED to fail:
# the trusted parent rejects it, the session driver stops on the first non-zero
# leg, and a shared session would report that designed rejection as a broken
# run.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

base_sha="8d938c911df52b6a324f259a55dbaa75e508c822"
export E66_BASE_SHA="${E66_BASE_SHA:-${base_sha}}"
export E42_BASE_SHA="${E42_BASE_SHA:-${base_sha}}"
export E66_ARMS_MODULE="research/e78_arms.py"
export E66_MANIFEST_DIR="${PWD}/.mlxfast-private/e78/arms"
export MLXFAST_LOCAL_RUN_LOCK_DIR="${MLXFAST_LOCAL_RUN_LOCK_DIR:-/tmp/mlxfast-shared}"

phase="${1:-all}"

if [[ "${phase}" == "all" || "${phase}" == "--golden-only" ]]; then
  echo "=== e78_rung1: golden leg (a_ship, ungated, not a measurement) ==="
  E66_WANDB=0 \
  E78_COOL_GATE=0 \
  E66_LEG_RUNNER="research/e78-run.sh" \
    research/e66_whole_leg_session.sh a_ship:golden:1
fi

if [[ "${phase}" == "all" || "${phase}" == "--ledgers-only" ]]; then
  golden="${PWD}/.mlxfast-private/e78/runs/golden/reports/leg-1/02-mtp-verify-output.json"
  [[ -r "${golden}" ]] || {
    echo "e78_rung1: no golden at ${golden}; run --golden-only first" >&2
    exit 1; }

  echo "=== e78_rung1: ledger legs against ${golden} ==="
  E66_WANDB=0 \
  E78_LEDGER_GOLDEN="${golden}" \
  E66_LEG_RUNNER="research/e78_ledger_leg.sh" \
    research/e66_whole_leg_session.sh \
      a_ship:a_ship:1 \
      c_hybrid24928:c_hybrid24928:1 \
      d_hybrid8192:d_hybrid8192:1
  timed_status=$?
  ((timed_status == 0)) || {
    echo "e78_rung1: the timed arms failed (${timed_status})" >&2; exit "${timed_status}"; }

  echo "=== e78_rung1: positive control (a rejection here is the pass) ==="
  E66_WANDB=0 \
  E78_LEDGER_GOLDEN="${golden}" \
  E66_LEG_RUNNER="research/e78_ledger_leg.sh" \
    research/e66_whole_leg_session.sh c_perturb:c_perturb:1
  control_status=$?
  ((control_status != 0)) || {
    echo "e78_rung1: the positive control passed; the instrument cannot detect a lane swap" >&2
    exit 1; }
  echo "e78_rung1: positive control rejected as designed (exit ${control_status})"
fi

python3 research/e78_exactness.py --out research/e78-artifacts/exactness.json
