#!/usr/bin/env python3
"""Regenerate three results that were settled when PR #7 and PR #10 merged.

1. The null calibration that REFUTED the advisor's "6.0x tighter" statistic
   in the PR #10 brief (qwen-thorfinn was right; this reproduces his numbers).
2. The cross-PR knee reconciliation: PR #7 measures M=1 (bandwidth-bound),
   PR #10 measures M=4,8 (ALU-bound). Same knee, opposite sides, mutual
   out-of-sample confirmation.
3. The acceptance break-even floors that PR #11 uses as its decision rule.

No dependencies. Runs in under a second. Every number printed here is quoted
somewhere in research/ESTABLISHED_FACTS.md; if this script and the prose
disagree, THIS SCRIPT IS THE AUTHORITY and the prose is stale.
"""

import math
import statistics as st


def rsd(v):
    """Relative standard deviation, percent."""
    return st.stdev(v) / st.mean(v) * 100.0


def rule(v):
    print("\n" + v)
    print("=" * len(v))


# ---------------------------------------------------------------------------
# 1. The advisor's decision rule, and its null calibration.
# ---------------------------------------------------------------------------
# From the NA=4 control recorded at research/ESTABLISHED_FACTS.md:1192-1195.
M = [4, 5, 8, 9]
STREAMS = [math.ceil(m / 4) for m in M]          # the integer staircase
CORRECTED = [165.6, 262.1, 183.0, 239.5]         # gbps_stream_corrected
NOMINAL = [c / s for c, s in zip(CORRECTED, STREAMS)]

rule("1. Three hypotheses scored on the advisor's own four points")
H_A = NOMINAL                                     # flat nominal  (pure bandwidth)
H_C = CORRECTED                                   # nominal x ceil(M/4) (streams)
H_B = [n * m for n, m in zip(NOMINAL, M)]         # nominal x M   (pure ALU)

print("  M                : %s" % M)
print("  nominal GB/s     : %s" % [round(x, 2) for x in NOMINAL])
print("  H_A flat nominal : rsd %6.2f%%" % rsd(H_A))
print("  H_C nominal*ceil : rsd %6.2f%%" % rsd(H_C))
print("  H_B nominal*M    : rsd %6.2f%%   (mean %.2f)" % (rsd(H_B), st.mean(H_B)))
print()
print("  advisor advertised : %.2fx tighter  (H_A / H_B)  <-- scored a STRAW competitor" % (rsd(H_A) / rsd(H_B)))
print("  honest margin      : %.2fx tighter  (H_C / H_B)  <-- vs the model actually rejected" % (rsd(H_C) / rsd(H_B)))

rule("2. Null calibration: run the advisor rule on data generated BY H_C")
print("  If the rule were unbiased it would report ~1.0x on integer-stream data.")
for label, Ms in (("M={4,5,8,9}", [4, 5, 8, 9]),
                  ("M=4..9", list(range(4, 10))),
                  ("M=1..9", list(range(1, 10)))):
    t = [math.ceil(m / 4) for m in Ms]
    nom = [1.0 / x for x in t]                    # noise-free, exactly H_C
    nomM = [n * m for n, m in zip(nom, Ms)]
    print("    %-12s rule reports %.1fx tighter" % (label, rsd(nom) / rsd(nomM)))
print()
print("  => the rule's FLOOR is 2.2x, not 1.0x. The advertised 6.0x was never")
print("     6.0x of anything. Honest claim: 3.8x against a 2.2x floor.")
print("     Credit: qwen-thorfinn, PR #10 evidence-contract item 4.")

rule("3. The integer-stream model dies on physics, independently")
for who, peak in (("PR #10 (thorfinn) STREAM peak", 226.9),
                  ("PR #7  (askeladd) STREAM peak", 227.128791836997),
                  ("spec roofline the advisor quoted", 273.0)):
    verdict = "IMPOSSIBLE" if 262.1 > peak else "possible"
    print("    M=5 stream-corrected 262.1 GB/s vs %-32s %6.1f -> %s" % (who, peak, verdict))
print()
print("  ADVISOR ERROR: the PR #10 brief told the student to score against the")
print("  273 GB/s SPEC roofline. Against 273 the impossibility vanishes. He got")
print("  the decisive check by declining to use the denominator he was handed.")
print("  Two independent students measured achievable peak 0.1% apart.")

# ---------------------------------------------------------------------------
# 4. Cross-PR knee reconciliation.
# ---------------------------------------------------------------------------
rule("4. PR #7 and PR #10 confirm each other across the knee")
KNEE_LO, KNEE_HI = 2.99, 3.27
rows = [
    ("PR #7  compact draft head readout", 1, "flat GB/s 243.0/249.4/234.4; bytes -25%/-50% -> time -24.2%/-42.4%"),
    ("PR #10 crossrow verify kernel", 4, "bytes -4x -> time -0.6%; ops -2.7x -> time -24.0%"),
    ("PR #10 crossrow verify kernel", 8, "bytes -4x -> time -0.3%; ops -2.7x -> time -49.4%"),
]
print("  knee band from PR #10 brief: [%.2f, %.2f]" % (KNEE_LO, KNEE_HI))
print()
for name, m, obs in rows:
    predicted = "bandwidth-bound" if m < KNEE_LO else "ALU-bound"
    print("    M=%d  %-34s predict %-15s" % (m, name, predicted))
    print("          observed: %s" % obs)
print()
print("  Both predictions hold. PR #7's sweep uses syntheticActivations(m: 1, k: 5120)")
print("  (Tests/MLXFastTests/QwenQMVCostCurveTests.swift), i.e. M=1 -- verified, not assumed.")
print()
print("  FORWARD PREDICTION (recorded, not yet tested): applying the low-bit trick")
print("  to the VERIFY-side head at M=4..9 buys ~0, against 24-42% at the draft")
print("  head. This is why no session is being spent on it.")

# ---------------------------------------------------------------------------
# 5. Acceptance break-even floors (PR #11 decision rule).
# ---------------------------------------------------------------------------
rule("5. Break-even acceptance floors for the low-bit draft head")
ACCEPTED, REJECTED, ROUNDS = 430, 53, 82
READOUTS = 483
A_CTL = ACCEPTED / (ACCEPTED + REJECTED)
tokens_per_round = 1 + ACCEPTED / ROUNDS
readouts_per_round = READOUTS / ROUNDS

print("  control accepted_draft_rate a0 = %.16f" % A_CTL)
print("  tokens/round   = 1 + %d/%d = %.4f" % (ACCEPTED, ROUNDS, tokens_per_round))
print("  readouts/round = %d/%d      = %.4f" % (READOUTS, ROUNDS, readouts_per_round))
print("  d(tokens/round)/da = %.3f ; relative sensitivity = %.3f"
      % (readouts_per_round, readouts_per_round / tokens_per_round))
print()
sens = readouts_per_round / tokens_per_round
for bits, saving in ((3, 0.007574), (2, 0.013269)):
    drop = saving / sens
    print("  %d-bit: saves %.4f%% -> break-even absolute drop %.5f -> FLOOR %.5f"
          % (bits, saving * 100, drop, A_CTL - drop))
print()
print("  CAVEAT (must travel with these numbers): this prices a rejected draft as")
print("  a lost token only. A rejection also forces rollback and re-forward, so")
print("  true degradation is worse than linear in a. Treat the floors as SOFT:")
print("  an arm landing NEAR its floor is a loss, not a win.")

rule("6. Part B of PR #11 is decisive by construction")
CTL_MS, B3_MS, NOISE_MS = 35.119320498779416, 34.45143951103091, 0.0137
print("  4-bit control      %.4f ms/token" % CTL_MS)
print("  3-bit arm          %.4f ms/token" % B3_MS)
print("  separation         %.4f ms/token = %.1fx the 0.0137 control-vs-control noise"
      % (CTL_MS - B3_MS, (CTL_MS - B3_MS) / NOISE_MS))
print("  => the unset-env default-path arm cannot land ambiguously.")
print("     ~34.45 = banked ; ~35.12 = default path not live ; worse = requantize")
print("     cost is inside scored time and the flip is net-negative.")
print()
